### ISSUE TITLE
[BUG] training a MultimodalPredictor results in RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)` when using multiple GPU's (but not when using only a single GPU)

### ISSUE THREAD

**Issue by hugocool** [autogluon/autogluon#2979] opened 2023-02-27 17:49 UTC
- [ x ] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
When I train a MultimodalPredictor I get `CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)` .
This only happens on instances with multiple GPU's, if i ran the same training script on instances with a single GPU (and the exact same environment) this issue does not happen.
In addition, when the model used the default hf_text model, this issue does not happen, but when i use a hugging face pretrained roberta transformers the issue occurs.
So it is a combination of the roberta transformers and distributed training. The issue does not occur on a single GPU and also doesn't occur when using electra/base.

**Expected behavior**
I expect the model to train on the different GPU's at the same time.

**Traceback**
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/ec2-user/anaconda3/envs/pytorch_p39/bin/kedro:8 in <module>                                │
│                                                                                                  │
│   5 from kedro.framework.cli import main                                                         │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(main())                                                                         │
│   9                                                                                              │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/framework/cli/cli.py │
│ :211 in main                                                                                     │
│                                                                                                  │
│   208 │   """                                                                                    │
│   209 │   _init_plugins()                                                                        │
│   210 │   cli_collection = KedroCLI(project_path=Path.cwd())                                     │
│ ❱ 211 │   cli_collection()                                                                       │
│   212                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/click/core.py:1128 in      │
│ __call__                                                                                         │
│                                                                                                  │
│   1125 │                                                                                         │
│   1126 │   def __call__(self, *args: t.Any, **kwargs: t.Any) -> t.Any:                           │
│   1127 │   │   """Alias for :meth:`main`."""                                                     │
│ ❱ 1128 │   │   return self.main(*args, **kwargs)                                                 │
│   1129                                                                                           │
│   1130                                                                                           │
│   1131 class Command(BaseCommand):                                                               │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/framework/cli/cli.py │
│ :139 in main                                                                                     │
│                                                                                                  │
│   136 │   │   )                                                                                  │
│   137 │   │                                                                                      │
│   138 │   │   try:                                                                               │
│ ❱ 139 │   │   │   super().main(                                                                  │
│   140 │   │   │   │   args=args,                                                                 │
│   141 │   │   │   │   prog_name=prog_name,                                                       │
│   142 │   │   │   │   complete_var=complete_var,                                                 │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/click/core.py:1053 in main │
│                                                                                                  │
│   1050 │   │   try:                                                                              │
│   1051 │   │   │   try:                                                                          │
│   1052 │   │   │   │   with self.make_context(prog_name, args, **extra) as ctx:                  │
│ ❱ 1053 │   │   │   │   │   rv = self.invoke(ctx)                                                 │
│   1054 │   │   │   │   │   if not standalone_mode:                                               │
│   1055 │   │   │   │   │   │   return rv                                                         │
│   1056 │   │   │   │   │   # it's not safe to `ctx.exit(rv)` here!                               │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/click/core.py:1659 in      │
│ invoke                                                                                           │
│                                                                                                  │
│   1656 │   │   │   │   super().invoke(ctx)                                                       │
│   1657 │   │   │   │   sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)                    │
│   1658 │   │   │   │   with sub_ctx:                                                             │
│ ❱ 1659 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub_ctx))               │
│   1660 │   │                                                                                     │
│   1661 │   │   # In chain mode we create the contexts step by step, but after the                │
│   1662 │   │   # base command has been invoked.  Because at that point we do not                 │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/click/core.py:1395 in      │
│ invoke                                                                                           │
│                                                                                                  │
│   1392 │   │   │   echo(style(message, fg="red"), err=True)                                      │
│   1393 │   │                                                                                     │
│   1394 │   │   if self.callback is not None:                                                     │
│ ❱ 1395 │   │   │   return ctx.invoke(self.callback, **ctx.params)                                │
│   1396 │                                                                                         │
│   1397 │   def shell_complete(self, ctx: Context, incomplete: str) -> t.List["CompletionItem"]:  │
│   1398 │   │   """Return a list of completions for the incomplete value. Looks                   │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/click/core.py:754 in       │
│ invoke                                                                                           │
│                                                                                                  │
│    751 │   │                                                                                     │
│    752 │   │   with augment_usage_errors(__self):                                                │
│    753 │   │   │   with ctx:                                                                     │
│ ❱  754 │   │   │   │   return __callback(*args, **kwargs)                                        │
│    755 │                                                                                         │
│    756 │   def forward(                                                                          │
│    757 │   │   __self, __cmd: "Command", *args: t.Any, **kwargs: t.Any  # noqa: B902             │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/framework/cli/projec │
│ t.py:382 in run                                                                                  │
│                                                                                                  │
│   379 │   node_names = _get_values_as_tuple(node_names) if node_names else node_names            │
│   380 │                                                                                          │
│   381 │   with KedroSession.create(env=env, extra_params=params) as session:                     │
│ ❱ 382 │   │   session.run(                                                                       │
│   383 │   │   │   tags=tag,                                                                      │
│   384 │   │   │   runner=runner(is_async=is_async),                                              │
│   385 │   │   │   node_names=node_names,                                                         │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/framework/session/se │
│ ssion.py:404 in run                                                                              │
│                                                                                                  │
│   401 │   │   )                                                                                  │
│   402 │   │                                                                                      │
│   403 │   │   try:                                                                               │
│ ❱ 404 │   │   │   run_result = runner.run(                                                       │
│   405 │   │   │   │   filtered_pipeline, catalog, hook_manager, session_id                       │
│   406 │   │   │   )                                                                              │
│   407 │   │   │   self._run_called = True                                                        │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/runner/runner.py:88  │
│ in run                                                                                           │
│                                                                                                  │
│    85 │   │   │   self._logger.info(                                                             │
│    86 │   │   │   │   "Asynchronous mode is enabled for loading and saving data"                 │
│    87 │   │   │   )                                                                              │
│ ❱  88 │   │   self._run(pipeline, catalog, hook_manager, session_id)                             │
│    89 │   │                                                                                      │
│    90 │   │   self._logger.info("Pipeline execution completed successfully.")                    │
│    91                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/runner/sequential_ru │
│ nner.py:70 in _run                                                                               │
│                                                                                                  │
│   67 │   │                                                                                       │
│   68 │   │   for exec_index, node in enumerate(nodes):                                           │
│   69 │   │   │   try:                                                                            │
│ ❱ 70 │   │   │   │   run_node(node, catalog, hook_manager, self._is_async, session_id)           │
│   71 │   │   │   │   done_nodes.add(node)                                                        │
│   72 │   │   │   except Exception:                                                               │
│   73 │   │   │   │   self._suggest_resume_scenario(pipeline, done_nodes, catalog)                │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/runner/runner.py:304 │
│ in run_node                                                                                      │
│                                                                                                  │
│   301 │   if is_async:                                                                           │
│   302 │   │   node = _run_node_async(node, catalog, hook_manager, session_id)                    │
│   303 │   else:                                                                                  │
│ ❱ 304 │   │   node = _run_node_sequential(node, catalog, hook_manager, session_id)               │
│   305 │                                                                                          │
│   306 │   for name in node.confirms:                                                             │
│   307 │   │   catalog.confirm(name)                                                              │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/runner/runner.py:398 │
│ in _run_node_sequential                                                                          │
│                                                                                                  │
│   395 │   )                                                                                      │
│   396 │   inputs.update(additional_inputs)                                                       │
│   397 │                                                                                          │
│ ❱ 398 │   outputs = _call_node_run(                                                              │
│   399 │   │   node, catalog, inputs, is_async, hook_manager, session_id=session_id               │
│   400 │   )                                                                                      │
│   401                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/runner/runner.py:366 │
│ in _call_node_run                                                                                │
│                                                                                                  │
│   363 │   │   │   is_async=is_async,                                                             │
│   364 │   │   │   session_id=session_id,                                                         │
│   365 │   │   )                                                                                  │
│ ❱ 366 │   │   raise exc                                                                          │
│   367 │   hook_manager.hook.after_node_run(                                                      │
│   368 │   │   node=node,                                                                         │
│   369 │   │   catalog=catalog,                                                                   │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/runner/runner.py:356 │
│ in _call_node_run                                                                                │
│                                                                                                  │
│   353 ) -> Dict[str, Any]:                                                                       │
│   354 │   # pylint: disable=too-many-arguments                                                   │
│   355 │   try:                                                                                   │
│ ❱ 356 │   │   outputs = node.run(inputs)                                                         │
│   357 │   except Exception as exc:                                                               │
│   358 │   │   hook_manager.hook.on_node_error(                                                   │
│   359 │   │   │   error=exc,                                                                     │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/pipeline/node.py:353 │
│ in run                                                                                           │
│                                                                                                  │
│   350 │   │   # purposely catch all exceptions                                                   │
│   351 │   │   except Exception as exc:                                                           │
│   352 │   │   │   self._logger.error("Node '%s' failed with error: \n%s", str(self), str(exc))   │
│ ❱ 353 │   │   │   raise exc                                                                      │
│   354 │                                                                                          │
│   355 │   def _run_with_no_inputs(self, inputs: Dict[str, Any]):                                 │
│   356 │   │   if inputs:                                                                         │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/pipeline/node.py:344 │
│ in run                                                                                           │
│                                                                                                  │
│   341 │   │   │   elif isinstance(self._inputs, str):                                            │
│   342 │   │   │   │   outputs = self._run_with_one_input(inputs, self._inputs)                   │
│   343 │   │   │   elif isinstance(self._inputs, list):                                           │
│ ❱ 344 │   │   │   │   outputs = self._run_with_list(inputs, self._inputs)                        │
│   345 │   │   │   elif isinstance(self._inputs, dict):                                           │
│   346 │   │   │   │   outputs = self._run_with_dict(inputs, self._inputs)                        │
│   347                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/kedro/pipeline/node.py:384 │
│ in _run_with_list                                                                                │
│                                                                                                  │
│   381 │   │   │   │   f"{sorted(inputs.keys())}."                                                │
│   382 │   │   │   )                                                                              │
│   383 │   │   # Ensure the function gets the inputs in the correct order                         │
│ ❱ 384 │   │   return self._func(*(inputs[item] for item in node_inputs))                         │
│   385 │                                                                                          │
│   386 │   def _run_with_dict(self, inputs: Dict[str, Any], node_inputs: Dict[str, str]):         │
│   387 │   │   # Node inputs and provided run inputs should completely overlap                    │
│                                                                                                  │
│ /home/ec2-user/SageMaker/..../pipelines/machine_learning/nodes.py:77 in     │
│ train_autogluon_multimodal                                                                       │
│                                                                                                  │
│    74 │   │   
│    75 │   )                                                                                      │
│    76 │                                                                                          │
│ ❱  77 │   predictor.fit(                                                                         │
│    78 │   │   train_data,                                                                        │
│    79 │   │   column_types = column_types,                                                       │
│    80 │   │   hyperparameters=base_params['hyperparameters'],                                    │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/predi │
│ ctor.py:839 in fit                                                                               │
│                                                                                                  │
│    836 │   │   │   )                                                                             │
│    837 │   │   │   return predictor                                                              │
│    838 │   │                                                                                     │
│ ❱  839 │   │   self._fit(**_fit_args)                                                            │
│    840 │   │   training_end = time.time()                                                        │
│    841 │   │   self._total_train_time = training_end - training_start                            │
│    842 │   │   logger.info(f"Models and intermediate outputs are saved to {self._save_path} ")   │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/predi │
│ ctor.py:1386 in _fit                                                                             │
│                                                                                                  │
│   1383 │   │   │   │   ".* in the `DataLoader` init to improve performance.*",                   │
│   1384 │   │   │   )                                                                             │
│   1385 │   │   │   warnings.filterwarnings("ignore", "Checkpoint directory .* exists and is not  │
│ ❱ 1386 │   │   │   trainer.fit(                                                                  │
│   1387 │   │   │   │   task,                                                                     │
│   1388 │   │   │   │   datamodule=train_dm,                                                      │
│   1389 │   │   │   │   ckpt_path=ckpt_path if resume else None,  # this is to resume training t  │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/ │
│ trainer.py:696 in fit                                                                            │
│                                                                                                  │
│    693 │   │   │   datamodule: An instance of :class:`~pytorch_lightning.core.datamodule.Lightn  │
│    694 │   │   """                                                                               │
│    695 │   │   self.strategy.model = model                                                       │
│ ❱  696 │   │   self._call_and_handle_interrupt(                                                  │
│    697 │   │   │   self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_  │
│    698 │   │   )                                                                                 │
│    699                                                                                           │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/ │
│ trainer.py:648 in _call_and_handle_interrupt                                                     │
│                                                                                                  │
│    645 │   │   """                                                                               │
│    646 │   │   try:                                                                              │
│    647 │   │   │   if self.strategy.launcher is not None:                                        │
│ ❱  648 │   │   │   │   return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **  │
│    649 │   │   │   else:                                                                         │
│    650 │   │   │   │   return trainer_fn(*args, **kwargs)                                        │
│    651 │   │   # TODO(awaelchli): Unify both exceptions below, where `KeyboardError` doesn't re  │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/strategi │
│ es/launchers/multiprocessing.py:107 in launch                                                    │
│                                                                                                  │
│   104 │   │   else:                                                                              │
│   105 │   │   │   process_args = [trainer, function, args, kwargs, return_queue]                 │
│   106 │   │                                                                                      │
│ ❱ 107 │   │   mp.start_processes(                                                                │
│   108 │   │   │   self._wrapping_function,                                                       │
│   109 │   │   │   args=process_args,                                                             │
│   110 │   │   │   nprocs=self._strategy.num_processes,                                           │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/multiprocessing/spaw │
│ n.py:198 in start_processes                                                                      │
│                                                                                                  │
│   195 │   │   return context                                                                     │
│   196 │                                                                                          │
│   197 │   # Loop on join until it returns True or raises an exception.                           │
│ ❱ 198 │   while not context.join():                                                              │
│   199 │   │   pass                                                                               │
│   200                                                                                            │
│   201                                                                                            │
│                                                                                                  │
│ /home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/multiprocessing/spaw │
│ n.py:160 in join                                                                                 │
│                                                                                                  │
│   157 │   │   original_trace = self.error_queues[error_index].get()                              │
│   158 │   │   msg = "\n\n-- Process %d terminated with the following error:\n" % error_index     │
│   159 │   │   msg += original_trace                                                              │
│ ❱ 160 │   │   raise ProcessRaisedException(msg, error_index, failed_process.pid)                 │
│   161                                                                                            │
│   162                                                                                            │
│   163 class SpawnContext(ProcessContext):                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/multiprocessing.py", line 133, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1166, in _run
    results = self._run_stage()
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1252, in _run_stage
    return self._run_train()
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1274, in _run_train
    self._run_sanity_check()
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_sanity_check
    val_loop.run()
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 155, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 200, in run
    self.advance(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 143, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 240, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1704, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/strategies/ddp_spawn.py", line 295, in validation_step
    return self.model(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1008, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 969, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/pytorch_lightning/overrides/base.py", line 90, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/optimization/lit_module.py", line 252, in validation_step
    output, loss = self._shared_step(batch)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/optimization/lit_module.py", line 209, in _shared_step
    output = run_model(self.model, batch)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/models/utils.py", line 703, in run_model
    output = model(batch)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/models/huggingface_text.py", line 177, in forward
    outputs = self.model(
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 844, in forward
    encoder_outputs = self.encoder(
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 520, in forward
    layer_outputs = layer_module(
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 405, in forward
    self_attention_outputs = self.attention(
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 332, in forward
    self_outputs = self.self(
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/transformers/models/roberta/modeling_roberta.py", line 196, in forward
    mixed_query_layer = self.query(hidden_states)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/autogluon/multimodal/models/adaptation_layers.py", line 187, in forward
    hidden = F.linear(x, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`
```

**Comment by zhiqiangdon** [comment] 2023-03-06 18:50
@hugocool I can't reproduce this error with autogluon.multimodal v0.7. Could you try to reduce the `env.per_gpu_batch_size`, restart your instance, or reinstall autogluon.multimodal v0.7?

**Comment by hugocool** [comment] 2023-03-06 18:53
I will try that and report back this week.

___

Hugo Evers

**Comment by zhiqiangdon** [comment] 2023-05-01 18:34
@hugocool , is it resolved?

**Comment by shchur** [comment] 2024-06-27 11:20
Closing the issue assuming it's resolved.

**Closed by shchur** 2024-06-27 11:20 UTC
Labels: bug: unconfirmed, Needs Triage
