### ISSUE TITLE
AG TextPredictor latency issues

### ISSUE THREAD

**Issue by kaash-io** [autogluon/autogluon#2143] opened 2022-09-18 04:22 UTC
Hello team, when running inference using AG TextPredictor, I am seeing latency around 550ms for a single record. I noticed most of the time is spent on this part of prediction log -

```
2022-09-12T00:21:05,194 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - 
2022-09-12T00:21:05,298 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Predicting: 0it [00:00, ?it/s]
2022-09-12T00:21:05,298 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Predicting:   0%|          | 0/1 [00:00<?, ?it/s]
2022-09-12T00:21:05,322 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Predicting DataLoader 0:   0%|          | 0/1 [00:00<?, ?it/s]
2022-09-12T00:21:05,382 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 41.49it/s]
2022-09-12T00:21:05,382 [INFO ] W-model-1-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Predicting DataLoader 0: 100%|██████████| 1/1 [00:00<00:00, 11.91it/s]
2022-09-12T00:21:05,593 [INFO ] W-9000-model com.amazonaws.ml.mms.wlm.WorkerThread - Backend response time: 521
```

Internal team pointed out that it is due to trainer being created which calls the dataframe preprocessor, data processor, and dataloader to obtain the tensor consumable by the model. A workaround solution is to call model directly like below -

```
from autogluon.multimodal.data.collator import Dict

batch_size = len(input_df.index)
ag_predictor = model._predictor
data_dict = ag_predictor._df_preprocessor.transform_text(input_df)

item_data_tokens = []
for idx in range(batch_size):
# note if not using batch mode using collate_fn then convert records to torch tensor e.g. torch.from_numpy(val)
        data_token = ag_predictor._data_processors['text'][0](data_dict, idx, False)
        item_data_tokens.append(data_token)

collate_fn = Dict(ag_predictor._data_processors['text'][0].collate_fn())
batch_data_tokens = collate_fn(item_data_tokens)
predictions = ag_predictor._model(batch_data_tokens)['hf_text']['logits'].detach()
predictions_softmax = torch.softmax(predictions, dim=-1)
prediction_probs = pd.DataFrame(predictions_softmax.numpy())[1] # get only positive value probability. By index index 1 is postive value.
```

This improves the latency for single record (~ 130ms down from 550ms) but doesn't scale well for batch records (e.g. 1 record latency is 130ms, while 3 records is 265ms). However, default `predict` method has almost same latency for 1 record or 100 records. 

Some details about setup -
- Using SageMaker script mode with AWS DLC 
- Used GPU for training and inferencing. Tried multi GPU as well but it seems only single GPU gets used for inferencing. 
- Tested  using SageMaker Endpoint. Best performance was on G4 instances. 

I am looking for ways to get under 200ms latency for batch of 10 records.

**Comment by sxjscience** [comment] 2022-09-20 17:30
Thanks for creating the issue @kaash-io . We will first investigate the root cause. It might also be related to overheads in Sagemaker endpoints.

**Comment by sxjscience** [comment] 2022-09-22 21:18
Should be partially fixed by https://github.com/awslabs/autogluon/pull/2157.

**Comment by kaash-io** [comment] 2022-09-27 21:36
Thanks Xingjian! As team pointed out, GPU was not being used in work around solution so adding something like this helped bring latency down to 20ms for single and 40ms for 10 records. 

```
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
ag_predictor._model.to(device)
for k, v in batch_data_tokens.items():
    batch_data_tokens[k] = v.to(device)

```
I will keep using this work around solution until new DLC with fixed version is available. 

Feel free to close the issue. 

Thanks,
Prakash

**Closed** 2023-02-01 23:18 UTC
