### ISSUE TITLE
Attempting to recover lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).

### ISSUE THREAD

**Issue by mimicarina** [autogluon/autogluon#3400] opened 2023-07-14 20:49 UTC
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Hyperparameter tuning for NN_TORCH leads to @ray.remote error. AutoGluon initializes normally (recognizes type of problem, features, ...) but as soon as training starts, error appears and kernel dies:
```
core_worker.cc:569: :info_message: Attempting to recover 8 lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).
```

**Expected behavior**
TabularPredictor should skip hyperparameter tuning or provide output/warning instead of killing kernel.

**To Reproduce**
Python 3.10
autogluon==0.8.2

```
# Importing the libraries 
from autogluon.tabular import TabularPredictor, TabularDataset

# Load in the dataset
train_data = TabularDataset("https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv")

train_data = train_data.sample(n=1000, random_state=0)

hyperparameters = {'NN_TORCH': {'num_epochs': 10 }}  

hyperparameter_tune_kwargs = {  
    'num_trials': 1,
    'scheduler' : 'local',
    'searcher': 'auto',
}  

predictor = TabularPredictor(label="occupation", eval_metric='accuracy').fit(
    train_data,
    time_limit=10*60,
    hyperparameters=hyperparameters,
    hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
)
```
**Screenshots / Logs**
NA

**Installed Versions**
Libraries from `conda_pytorch_p310` kernel with added installation of autogluon==0.8.2.

```
absl-py==1.4.0
accelerate==0.16.0
aiofiles @ file:///home/conda/feedstock_root/build_artifacts/aiofiles_1664378549280/work
aiohttp==3.8.4
aiohttp-cors==0.7.0
aiosignal==1.3.1
aiosqlite @ file:///home/conda/feedstock_root/build_artifacts/aiosqlite_1682491975081/work
aniso8601==9.0.1
ansi2html==1.8.0
antlr4-python3-runtime==4.9.3
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1666191106763/work/dist
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1640817743617/work
argon2-cffi-bindings @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi-bindings_1666850768662/work
arrow==1.2.3
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
async-timeout==4.0.2
attrs==23.1.0
autogluon==0.8.2
autogluon.common==0.8.2
autogluon.core==0.8.2
autogluon.features==0.8.2
autogluon.multimodal==0.8.2
autogluon.tabular==0.8.2
autogluon.timeseries==0.8.2
autovizwidget==0.20.5
awscli==1.27.157
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1677767029043/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1680888073205/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1674535352125/work
blessed==1.20.0
blinker==1.6.2
blis==0.7.9
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1683730530224/work
boto3==1.26.157
botocore==1.29.157
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1666764671472/work
cachetools==5.3.1
captum @ file:///home/conda/feedstock_root/build_artifacts/captum_1676431791267/work
catalogue==2.0.8
catboost==1.2
certifi==2023.5.7
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1671179353105/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1678108872112/work
click==8.1.3
cloudpickle==2.2.1
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1602866480661/work
colorful==0.5.5
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1679481329611/work
confection==0.1.0
contextlib2==21.6.0
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1673633665736/work
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography-split_1677821274828/work
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1635519461629/work
cymem==2.0.7
datasets==2.13.1
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1680755465990/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
dill==0.3.6
distlib==0.3.6
docker==6.1.3
docutils @ file:///home/conda/feedstock_root/build_artifacts/docutils_1667993608396/work
dparse==0.6.2
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1643888246732/work
environment-kernels==1.2.0
evaluate==0.3.0
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
fastai==2.7.12
fastcore==1.5.29
fastdownload==0.0.7
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1677336799617/work/dist
fastprogress==1.0.3
filelock @ file:///home/conda/feedstock_root/build_artifacts/filelock_1681839547898/work
Flask==2.3.2
Flask-RESTful==0.3.9
flit_core @ file:///home/conda/feedstock_root/build_artifacts/flit-core_1667734568827/work/source/flit_core
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1680021152278/work
fqdn==1.5.1
frozenlist==1.4.0
fsspec==2023.5.0
future==0.18.3
gdown==4.7.1
gluonts==0.13.2
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1666808654411/work
google-api-core==2.11.1
google-auth==2.22.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
googleapis-common-protos==1.59.1
gpustat==1.1
graphviz==0.20.1
grpcio==1.50.0
gssapi==1.8.2
gym==0.26.2
gym-notices==0.0.8
hdijupyterutils==0.20.5
horovod==0.28.0
huggingface-hub==0.16.4
hyperopt==0.2.7
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1663625384323/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1683031833737/work
importlib-metadata==4.13.0
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1676919000169/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1683553336538/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1683225895562/work
ipython-genutils==0.2.0
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1680023138361/work
isoduration==20.11.0
itsdangerous==2.1.2
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1654302431367/work
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1655568249366/work
joblib==1.2.0
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonpointer==2.3
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema-meta_1669810440410/work
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/jupyter_events_1673559782596/work
jupyter-ydoc @ file:///home/conda/feedstock_root/build_artifacts/jupyter_ydoc_1679325289144/work/dist
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1681432441054/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1678994169527/work
jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1679073341944/work
jupyter_server_fileid @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_fileid_1681071667289/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1673491454549/work
jupyter_server_ydoc @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_ydoc_1678043727957/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1680263892608/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1649936611996/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1680020489668/work
jupyterlab_server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1681424698040/work
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1666805701884/work
krb5==0.5.0
langcodes==3.3.0
lightgbm==3.3.5
lightning-utilities==0.9.0
llvmlite==0.40.0
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1674135787083/work
matplotlib @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-suite_1678135565516/work
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
mdurl==0.1.2
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1675771498296/work
mlforecast==0.7.3
model-index==0.1.11
mpi4py==3.1.4
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1678228039184/work
msgpack==1.0.5
multidict==6.0.4
multiprocess==0.70.14
munkres==1.1.4
murmurhash==1.0.9
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1683202081046/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1682452223743/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert-meta_1683636231832/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1679336765223/work
nest-asyncio==1.5.5
networkx @ file:///home/conda/feedstock_root/build_artifacts/networkx_1680692919326/work
nlpaug==1.1.11
nltk==3.8.1
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1680870634737/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1682360583588/work
nptyping==2.4.1
numba==0.57.0
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1682210193659/work
nvgpu==0.10.0
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-ml-py==11.525.112
oauthlib==3.2.2
omegaconf==2.2.3
onnx @ file:///home/conda/feedstock_root/build_artifacts/onnx_1682690354537/work
opencensus==0.11.2
opencensus-context==0.1.3
opencv-python==4.6.0.66
opendatalab==0.0.9
openmim==0.3.9
ordered-set==4.1.0
packaging==21.3
pandas==1.5.3
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pathos==0.3.0
pathy==0.10.2
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1665356157073/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1667297516076/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==9.5.0
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1633981968097/work
platformdirs==3.8.1
plotly==5.14.1
pooch @ file:///home/conda/feedstock_root/build_artifacts/pooch_1679580333621/work
pox==0.3.2
ppft==1.7.6.6
preshed==3.0.8
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1674535637125/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
protobuf==3.20.2
protobuf3-to-dict==0.1.5
psutil @ file:///home/conda/feedstock_root/build_artifacts/psutil_1681775027942/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
py-spy==0.3.14
py4j==0.10.9.5
pyarrow==12.0.0
pyasn1==0.4.8
pyasn1-modules==0.3.0
pybind11 @ file:///home/conda/feedstock_root/build_artifacts/pybind11-split_1679012409253/work
pybind11-global @ file:///home/conda/feedstock_root/build_artifacts/pybind11-split_1679012409253/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pycryptodome==3.18.0
pydantic @ file:///home/conda/feedstock_root/build_artifacts/pydantic_1679565261911/work
pyfunctional==1.4.3
pygame==2.4.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1681904169130/work
pynvml==11.5.0
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1680037383858/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1652235407899/work
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1672681463845/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1661604839144/work
pyspark==3.3.0
pyspnego==0.9.0
pytesseract==0.3.10
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
pytorch-lightning==1.9.5
pytorch-metric-learning==1.7.3
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1680088766131/work
PyWavelets==1.4.1
PyYAML==5.4.1
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1679316826707/work
qtconsole==5.4.3
QtPy==2.3.1
ray==2.3.1
regex==2023.6.3
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1682535435083/work
requests-kerberos==0.14.0
requests-oauthlib==1.3.1
responses==0.18.0
rfc3339-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1638811747357/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rich==13.4.2
rsa @ file:///home/conda/feedstock_root/build_artifacts/rsa_1614171254180/work
ruamel.yaml==0.17.26
ruamel.yaml.clib==0.2.7
s3fs==0.4.2
s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1683241957497/work
safetensors==0.3.1
sagemaker==2.167.0
sagemaker-pyspark==1.4.5
schema==0.7.5
scikit-image==0.19.3
scikit-learn==1.2.2
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy_1683719288579/work/dist/scipy-1.10.1-cp310-cp310-linux_x86_64.whl#sha256=eeee39d8a01a8072da1efa959a1490fe1e94114fa147125c39cf3c438f69ca54
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1672497695270/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1682601222253/work
sentencepiece==0.1.99
seqeval==1.2.2
shap==0.40.0
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
slicer==0.0.7
smart-open==6.3.0
smclarify==0.5
smdebug-rulesconfig==1.0.1
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1662051266223/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1658207591808/work
spacy==3.6.0
spacy-legacy==3.0.12
spacy-loggers==1.0.4
sparkmagic==0.20.5
srsly==2.4.6
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
statsforecast==1.4.0
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1683305553485/work
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1679342590084/work
tabulate==0.9.0
tblib==1.7.0
tenacity==8.2.2
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorboardX==2.6
termcolor==2.3.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1670253674810/work
text-unidecode==1.3
thinc==8.1.10
threadpoolctl==3.1.0
tifffile==2023.7.10
timm==0.9.2
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1666100256010/work
tokenizers==0.13.3
toml==0.10.2
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1644342247877/work
toolz==0.12.0
torch==1.13.1
torch-model-archiver @ file:///usr/share/miniconda/conda-bld/torch-model-archiver_1675893865207/work
torch-workflow-archiver @ file:///usr/share/miniconda/conda-bld/torch-workflow-archiver_1675893922533/work
torchaudio==2.0.1
torchdata @ file:///opt/conda/conda-bld/torchdata_1679615656247/work
torchmetrics==0.11.4
torchserve @ file:///usr/share/miniconda/conda-bld/torchserve_1675893783892/work
torchtext==0.15.1
torchvision==0.14.1
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1681817446549/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1677948868469/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
transformers==4.26.1
triton==2.0.0
typer==0.9.0
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/typing_extensions_1678559861143/work
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1680081134351/work
ujson==5.7.0
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1667239886688/work
uri-template==1.2.0
urllib3==1.26.14
virtualenv==20.23.1
wasabi==1.1.2
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
webcolors==1.13
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1675567828044/work
Werkzeug==2.3.4
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1680021576815/work
window-ops==0.0.14
xgboost==1.7.6
xxhash==3.2.0
xyzservices @ file:///home/conda/feedstock_root/build_artifacts/xyzservices_1676835466992/work
y-py @ file:///home/conda/feedstock_root/build_artifacts/y-py_1677231008299/work
yarl==1.9.2
ypy-websocket @ file:///home/conda/feedstock_root/build_artifacts/ypy-websocket_1670333059911/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1677313463193/work
```

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

```
INSTALLED VERSIONS
------------------
date                   : 2023-07-14
time                   : 20:47:45.354256
python                 : 3.10.10.final.0
OS                     : Linux
OS-release             : 5.10.178-162.673.amzn2.x86_64
Version                : #1 SMP Mon Apr 24 23:34:06 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 8
cpu_ram_mb             : 31627
cuda version           : 12.525.85.12
num_gpus               : 1
gpu_ram_mb             : [15101]
avail_disk_size_mb     : 458522

accelerate             : 0.16.0
autogluon              : 0.8.2
autogluon.common       : 0.8.2
autogluon.core         : 0.8.2
autogluon.features     : 0.8.2
autogluon.multimodal   : 0.8.2
autogluon.tabular      : 0.8.2
autogluon.timeseries   : 0.8.2
boto3                  : 1.26.157
catboost               : 1.2
defusedxml             : 0.7.1
evaluate               : 0.3.0
fastai                 : 2.7.12
gluonts                : 0.13.2
grpcio                 : 1.50.0
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.1
mlforecast             : 0.7.3
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.3
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
pandas                 : 1.5.3
Pillow                 : 9.5.0
psutil                 : 5.9.4
pydantic               : 1.10.7
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 1.9.5
pytorch-metric-learning: 1.7.3
ray                    : 2.3.1
requests               : 2.29.0
scikit-image           : 0.19.3
scikit-learn           : 1.2.2
scikit-learn-intelex   : None
scipy                  : 1.10.1
seqeval                : 1.2.2
setuptools             : 67.7.2
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.0
tabpfn                 : None
tensorboard            : 2.13.0
text-unidecode         : 1.3
timm                   : 0.9.2
torch                  : 1.13.1
torchmetrics           : 0.11.4
torchvision            : 0.14.1
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.7.0
vowpalwabbit           : None
xgboost                : 1.7.6
```

**Comment by yinweisu** [comment] 2023-07-14 21:18
Hi, I was not able to reproduce this in a fresh 0.8.2 environment. This might come into something with your kernel. Are you running this in a sagemaker notebook?

**Comment by mimicarina** [comment] 2023-07-19 17:35
Yes, this is running in a SageMaker notebook. I indicated the kernel version in the initial report (`conda_pytorch_p310`).

**Comment by shahdhvani08** [comment] 2023-07-31 03:29
Hello, I am also experiencing the same issue when autogluon uses NeuralNetFastAI model. Any suggestion, please?

**Comment by shchur** [comment] 2024-06-27 10:52
I believe this bug has been fixed in the lates AG release (v1.1.1). Please feel free to re-open if that's not the case.

**Closed by shchur** 2024-06-27 10:52 UTC
Labels: module: tabular, bug: unconfirmed, Needs Triage
