### ISSUE TITLE
Error with HPO

### ISSUE THREAD

**Issue by giobrus** [autogluon/autogluon#3799] opened 2023-12-06 14:16 UTC
Hi everyone, I have encountered an error:

The cell I execute is:
`predictor = TabularPredictor(label='num', eval_metric='accuracy',path='run_6').fit(train_df, time_limit=86400, presets='best_quality',dynamic_stacking=True, hyperparameter_tune_kwargs='auto')`

but after a while, the output disapperas and then this error message pops out in the output cell:

2023-12-06 15:08:35,885	ERROR tune_controller.py:911 -- Trial task failed for trial 68be4a2f
Traceback (most recent call last):
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/_private/worker.py", line 2526, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
2023-12-06 15:08:35,900	ERROR tune_controller.py:911 -- Trial task failed for trial e12c7fe0
Traceback (most recent call last):
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/hdd/home/gbrus/.virtualenvs/pythonProject1/lib/python3.10/site-packages/ray/_private/worker.py", line 2526, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
[2023-12-06 15:08:48,918 E 2921676 2922173] core_worker.cc:587: :info_message: Attempting to recover 9 lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).

**Comment by rsj123** [comment] 2023-12-09 12:14
It looks like you are using multiple gpu, you may want to look for the output log from ray

**Comment by Innixma** [comment] 2024-04-02 21:58
Marked as resolved, insufficient info to be able to easily reproduce.

**Closed** 2024-04-02 21:57 UTC
Labels: module: tabular, bug: unconfirmed, Needs Triage
