### ISSUE TITLE
[BUG] ValueError: assignment destination is read-only when dynamic stacking is used with validation data

### ISSUE THREAD

**Issue by fplein** [autogluon/autogluon#3964] opened 2024-03-05 08:59 UTC
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**

Using the combination of `dynamic_stacking=True`, `tuning_data=some_dataframe` and `use_bag_holdout=True`, results in a `ValueError: assignment destination is read-only` in the `ray`-based subfit (triggered in the MWE when calling fit a second time in the same script). The exception seems to go away when setting in addition `ds_args={"memory_safe_fits": False}`, since no `ray`-based subfit appears in that case.

**Expected behavior**

No exception should be thrown whether using `ray`-based subfit or not.

**To Reproduce**

<details>

```python
import pandas
from autogluon.tabular import TabularPredictor

if __name__ == "__main__":
    train_data = pandas.DataFrame(
        [[1, 2, 0], [2, 5, 0], [3, 4, 0], [2, 1, 1], [7, 8, 0], [10, 8, 1], [3, 0, 1], [6, 5, 1]],
        columns=['a', 'b', 'label'])
    tuning_data = pandas.DataFrame(
        [[12, 2, 1], [5, 3, 1], [7, 9, 0], [5, 8, 0], [3, 0, 1]],
        columns=['a', 'b', 'label'])

    for _ in range(2):
        predictor = TabularPredictor(
            label="label",
            problem_type="binary",
            eval_metric="balanced_accuracy",
            verbosity=2
        )

        predictor.fit(
            presets='best_quality',
            time_limit=1000,
            hyperparameters={"XGB": {}},
            train_data=train_data,
            tuning_data=tuning_data,
            use_bag_holdout=True,
            # ds_args={"memory_safe_fits": False},
        )
```

</details>

**Screenshots / Logs**

First iteration log: 
<details>

```
No path specified. Models will be saved in: "AutogluonModels/ag-20240305_084505"
Presets specified: ['best_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1
Dynamic stacking is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
Detecting stacked overfitting by sub-fitting AutoGluon on the input data. That is, copies of AutoGluon will be sub-fit on subset(s) of the data. Then, the holdout validation data is used to detect stacked overfitting.
Sub-fit(s) time limit is: 1000 seconds.
Starting holdout-based sub-fit for dynamic stacking. Context path is: AutogluonModels/ag-20240305_084505/ds_sub_fit/sub_fit_ho.
Beginning AutoGluon training ... Time limit = 250s
AutoGluon will save models to "AutogluonModels/ag-20240305_084505/ds_sub_fit/sub_fit_ho"
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.8.10
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202205222030 SMP PREEMPT_DYNAMIC Sun May 22 20:33:46 UTC 2022
CPU Count:          20
Memory Avail:       41.70 GB / 62.61 GB (66.6%)
Disk Space Avail:   67.09 GB / 195.66 GB (34.3%)
===================================================
Train Data Rows:    7
Train Data Columns: 2
Tuning Data Rows:    5
Tuning Data Columns: 2
Label Column:       label
Problem Type:       binary
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 3 to avoid cutting too many classes.
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    42705.70 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 2 | ['a', 'b']
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 2 | ['a', 'b']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.01s ...
AutoGluon will gauge predictive performance using evaluation metric: 'balanced_accuracy'
	To change this, specify the eval_metric parameter of Predictor()
use_bag_holdout=True, will use tuning_data as holdout (will not be used for early stopping).
User-specified model hyperparameters to be fit:
{
	'XGB': {},
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 1 L1 models ...
Fitting model: XGBoost_BAG_L1 ... Training model for up to 166.62s of the 249.99s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
	0.5	 = Validation score   (balanced_accuracy)
	0.18s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 249.99s of the 246.4s of remaining time.
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.5	 = Validation score   (balanced_accuracy)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 1 L2 models ...
Fitting model: XGBoost_BAG_L2 ... Training model for up to 246.39s of the 246.39s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
	0.5	 = Validation score   (balanced_accuracy)
	0.19s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 249.99s of the 245.49s of remaining time.
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.5	 = Validation score   (balanced_accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 4.57s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240305_084505/ds_sub_fit/sub_fit_ho")
Leaderboard on holdout data from dynamic stacking:
                 model  holdout_score  score_val        eval_metric  pred_time_test  pred_time_val  fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0       XGBoost_BAG_L1            0.5        0.5  balanced_accuracy        0.021669       0.007717  0.180838                 0.021669                0.007717           0.180838            1       True          1
1  WeightedEnsemble_L3            0.5        0.5  balanced_accuracy        0.022523       0.008139  0.234446                 0.000854                0.000423           0.053608            3       True          4
2  WeightedEnsemble_L2            0.5        0.5  balanced_accuracy        0.022617       0.008014  0.182899                 0.000948                0.000297           0.002062            2       True          2
3       XGBoost_BAG_L2            0.5        0.5  balanced_accuracy        0.040267       0.015447  0.373177                 0.018597                0.007730           0.192339            2       True          3
Stacked overfitting occurred: False.
Spend 4 seconds for the sub-fit(s) during dynamic stacking.
Time left for full fit of AutoGluon: 996 seconds.
Starting full fit now with num_stack_levels 1.
Beginning AutoGluon training ... Time limit = 996s
AutoGluon will save models to "AutogluonModels/ag-20240305_084505"
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.8.10
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202205222030 SMP PREEMPT_DYNAMIC Sun May 22 20:33:46 UTC 2022
CPU Count:          20
Memory Avail:       40.97 GB / 62.61 GB (65.4%)
Disk Space Avail:   67.09 GB / 195.66 GB (34.3%)
===================================================
Train Data Rows:    8
Train Data Columns: 2
Tuning Data Rows:    5
Tuning Data Columns: 2
Label Column:       label
Problem Type:       binary
Preprocessing data ...
Warning: Updated label_count_threshold from 10 to 4 to avoid cutting too many classes.
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    41955.70 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 2 | ['a', 'b']
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 2 | ['a', 'b']
	0.0s = Fit runtime
	2 features in original data used to generate 2 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.01s ...
AutoGluon will gauge predictive performance using evaluation metric: 'balanced_accuracy'
	To change this, specify the eval_metric parameter of Predictor()
use_bag_holdout=True, will use tuning_data as holdout (will not be used for early stopping).
User-specified model hyperparameters to be fit:
{
	'XGB': {},
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 1 L1 models ...
Fitting model: XGBoost_BAG_L1 ... Training model for up to 663.83s of the 995.99s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
	0.5	 = Validation score   (balanced_accuracy)
	0.22s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 994.96s of remaining time.
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.5	 = Validation score   (balanced_accuracy)
	0.0s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 1 L2 models ...
Fitting model: XGBoost_BAG_L2 ... Training model for up to 994.95s of the 994.95s of remaining time.
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy (5 workers, per: cpus=4, gpus=0, memory=0.00%)
	0.5	 = Validation score   (balanced_accuracy)
	0.51s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the 993.82s of remaining time.
	Ensemble Weights: {'XGBoost_BAG_L1': 1.0}
	0.5	 = Validation score   (balanced_accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 2.23s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240305_084505")
```

</details>

Second iteration log: 
<details>

```
No path specified. Models will be saved in: "AutogluonModels/ag-20240305_084512"
Presets specified: ['best_quality']
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=5, num_bag_sets=1
Dynamic stacking is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
Detecting stacked overfitting by sub-fitting AutoGluon on the input data. That is, copies of AutoGluon will be sub-fit on subset(s) of the data. Then, the holdout validation data is used to detect stacked overfitting.
Sub-fit(s) time limit is: 1000 seconds.
Starting holdout-based sub-fit for dynamic stacking. Context path is: AutogluonModels/ag-20240305_084512/ds_sub_fit/sub_fit_ho.
Running the sub-fit in a ray process to avoid memory leakage.
Traceback (most recent call last):
  File "/home/fplein/python/autogluon/src/autogluon/MWE.py", line 22, in <module>
    predictor.fit(
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/core/utils/decorators.py", line 31, in _call
    return f(*gargs, **gkwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 1099, in fit
    num_stack_levels, time_limit = self._dynamic_stacking(**ds_args, ag_fit_kwargs=ag_fit_kwargs, ag_post_fit_kwargs=ag_post_fit_kwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 1186, in _dynamic_stacking
    stacked_overfitting = self._sub_fit_memory_save_wrapper(
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 1329, in _sub_fit_memory_save_wrapper
    stacked_overfitting = _ds_ray.get(finished[0])
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/ray/_private/worker.py", line 2524, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ValueError): ray::_sub_fit() (pid=1992021, ip=136.243.37.56)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 4897, in _sub_fit
    predictor._fit(ag_fit_kwargs=ag_fit_kwargs, ag_post_fit_kwargs=ag_post_fit_kwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/predictor/predictor.py", line 1115, in _fit
    self._learner.fit(**ag_fit_kwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/learner/abstract_learner.py", line 159, in fit
    return self._fit(X=X, X_val=X_val, **kwargs)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/learner/default_learner.py", line 93, in _fit
    X, y, X_val, y_val, X_unlabeled, holdout_frac, num_bag_folds, groups = self.general_data_processing(X, X_val, X_unlabeled, holdout_frac, num_bag_folds)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/autogluon/tabular/learner/default_learner.py", line 198, in general_data_processing
    X_val[self.label].replace([np.inf, -np.inf], np.nan, inplace=True)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/series.py", line 5223, in replace
    return super().replace(
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/generic.py", line 7399, in replace
    return self._update_inplace(result)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/generic.py", line 4660, in _update_inplace
    self._maybe_update_cacher(verify_is_copy=verify_is_copy, inplace=True)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/series.py", line 1361, in _maybe_update_cacher
    ref._maybe_cache_changed(cacher[0], self, inplace=inplace)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/frame.py", line 4280, in _maybe_cache_changed
    self._mgr.iset(loc, arraylike, inplace=inplace)
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1213, in iset
    blk.set_inplace(blk_locs, value_getitem(val_locs))
  File "/home/fplein/.pipenv/autogluon-ne15dTxy/lib/python3.8/site-packages/pandas/core/internals/blocks.py", line 924, in set_inplace
    self.values[locs] = values
ValueError: assignment destination is read-only
```

</details>

**Installed Versions**

<details>

INSTALLED VERSIONS
------------------
date                : 2024-03-05
time                : 09:41:32.456414
python              : 3.8.10.final.0
OS                  : Linux
OS-release          : 5.18.0-051800-generic
Version             : #202205222030 SMP PREEMPT_DYNAMIC Sun May 22 20:33:46 UTC 2022
machine             : x86_64
processor           : x86_64
num_cores           : 20
cpu_ram_mb          : 64116.89453125
cuda version        : None
num_gpus            : 0
gpu_ram_mb          : []
avail_disk_size_mb  : 68699

async-timeout       : 4.0.3
autogluon           : None
autogluon.common    : 1.0.0
autogluon.core      : 1.0.0
autogluon.features  : 1.0.0
autogluon.tabular   : 1.0.0
boto3               : 1.33.11
catboost            : 1.2.2
fastai              : 2.7.13
hyperopt            : 0.2.7
imodels             : 1.3.18
lightgbm            : 4.1.0
matplotlib          : 3.7.4
networkx            : 3.1
numpy               : 1.24.4
onnxruntime-gpu     : 1.15.1
pandas              : 2.0.3
psutil              : 5.9.6
ray                 : 2.6.3
requests            : 2.31.0
scikit-learn        : 1.3.2
scikit-learn-intelex: 2024.0.1
scipy               : 1.10.1
setuptools          : 69.0.2
skl2onnx            : 1.15.0
tabpfn              : 0.1.9
torch               : 2.0.1+cpu
tqdm                : 4.66.1
vowpalwabbit        : 9.8.0
xgboost             : 2.0.2

</details>

**Comment by Innixma** [comment] 2024-04-16 22:52
Thanks for the reproducible script @fplein!

I was able to reproduce the error with AutoGluon 1.0

I tested with latest mainline and the issue has been fixed, likely due to #3774.
This should be resolved in the AutoGluon 1.1 release.

Code to reproduce with AutoGluon 1.1 (need to specify `dynamic_stacking=True` to force enable)

```python3
import pandas
from autogluon.tabular import TabularPredictor

if __name__ == "__main__":
    train_data = pandas.DataFrame(
        [[1, 2, 0], [2, 5, 0], [3, 4, 0], [2, 1, 1], [7, 8, 0], [10, 8, 1], [3, 0, 1], [6, 5, 1]],
        columns=['a', 'b', 'label'])
    tuning_data = pandas.DataFrame(
        [[12, 2, 1], [5, 3, 1], [7, 9, 0], [5, 8, 0], [3, 0, 1]],
        columns=['a', 'b', 'label'])

    for _ in range(2):
        predictor = TabularPredictor(
            label="label",
            problem_type="binary",
            eval_metric="balanced_accuracy",
            verbosity=2
        )

        predictor.fit(
            presets='best_quality',
            time_limit=1000,
            hyperparameters={"XGB": {}},
            train_data=train_data,
            tuning_data=tuning_data,
            use_bag_holdout=True,
            dynamic_stacking=True,
            # ds_args={"memory_safe_fits": False},
        )
```

**Closed by Innixma** 2024-04-16 22:52 UTC
Labels: module: tabular, bug: unconfirmed, Needs Triage
