### ISSUE TITLE
[Bug] Tabular + images for regression?

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#1546] opened 2022-02-18 20:21 UTC
### Discussed in https://github.com/awslabs/autogluon/discussions/1545

<div type='discussions-op-text'>

<sup>Originally posted by **xibux-repo** February 18, 2022</sup>
Dear autogluon team, 

I just come across this problem, is it possible to use tabular and images for regression problem? I think the current version only support tabular+image for classification, coz in my initial try when I set the problem_type='regression', the image predictor just failed, other models are fine.  

Best
Xibin </div>

**Comment by xibux-repo** [comment] 2022-02-21 12:11
Thanks! Hopefully we could test it in the new release.

**Comment by yinweisu** [comment] 2022-02-22 01:15
Hi, I wasn't able to reproduce this issue with both autogluon==0.3.1 and current master branch. Is it possible for you to share the dataset so that I can try to reproduce?

**Comment by janeyoung2018** [comment] 2022-02-22 10:59
> 

We use the version 0.3.1. It's because our output values are between 5000-500000, during the training, the rmse=nan. When I log(output), it works fine. But for other mutimodal models including text-predictor, there are no such problems. I changed the loss function of image-classification to L1Loss(mae) it works.

Another problem of multimodal tabular prediction(tabular+text+image) is that when goes to image-prediction, cuda would out of memory even for small dataset(1000 rows). Add "import gc gc.collect() torch.cuda.empty_cache()"  could solve the problem for small dataset(tried up to 20k). But for large dataset the same error appears again. 

Thanks.

**Comment by yinweisu** [comment] 2022-02-22 18:32
OK. I tested multi modality with text predictor being disabled and rmse worked fine.

This should be improved for the next release. The usage of both mxnet(text) and torch(image) backend is competing for resources and could cause weird OOM issue.

**Comment by Innixma** [comment] 2022-02-22 21:19
@sxjscience and @zhiqiangdon we may want to check if AutoMM Image model can handle very large target values for RMSE, I'm guessing ImagePredictor gets overflow due to the value of RMSE being too large.

**Comment by janeyoung2018** [comment] 2022-02-23 17:51
Another question, if I understand right, the image predictor model for tabular prediction includes only image as input feature, numerical and categorical inputs are not included, right? Will you add other features in the upcoming version? Thanks.

**Comment by zhiqiangdon** [comment] 2022-02-23 20:18
@janeyoung2018 You can try our new AutoMMPredictor (already merged into the main branch) for image+tabular regression. Basically, AutoMM can cover any combinations of image, text, numerical, and categorical features. For each combination, it can support both classification and regression. I am writing a tutorial about how to use AutoMM.

**Comment by janeyoung2018** [comment] 2022-02-23 20:50
Cool, thanks.

**Comment by janeyoung2018** [comment] 2022-02-23 20:59
> @janeyoung2018 You can try our new AutoMMPredictor (already merged into the main branch) for image+tabular regression. Basically, AutoMM can cover any combinations of image, text, numerical, and categorical features. For each combination, it can support both classification and regression. I am writing a tutorial about how to use AutoMM.

Cool, thanks, I will try.

**Closed** 2023-02-01 21:26 UTC
Labels: module: vision, bug: unconfirmed
