### ISSUE TITLE
How can I log to file?

### ISSUE THREAD

**Issue by marcofrancis** [autogluon/autogluon#3221] opened 2023-05-18 09:24 UTC
### Describe the issue linked to the documentation

Hi, in the docs it is often mentioned that "If using logging, you can alternatively control amount of information printed via logger.setLevel(L), where L ranges from 0 to 50 (Note: higher values of L correspond to fewer print statements, opposite of verbosity levels)". How do I use a logger with autogluon? What steps should I follow? I cannot find anything in the docs.

### Suggest a potential alternative/fix

Add a section about logging to the docs

**Comment by yinweisu** [comment] 2023-05-22 18:38
Hi,
You can control level of logging either with predictor `init()` call, i.e `predictor = TabularPredictor(..., verbose=3)`, or through the logger directly, i.e. `logger = logging.getLogger("autogluon"); logger.setLevel(30)`

Regarding logging to file, there's no support currently and is a duplicate of https://github.com/autogluon/autogluon/issues/3127. We'll be looking into supporting it

**Comment by yinweisu** [comment] 2023-05-30 16:34
We have added support for logging to file and will be available after next release.
To use it, you can do `predictor = TabularPredictor(..., log_to_file=True)`

**Closed by yinweisu** 2023-05-30 16:34 UTC
Labels: API & Doc, Needs Triage

**Comment by Hallvaeb** [comment] 2023-11-09 19:08
#  
Hi! I'm getting 
"
ValueError: Invalid kwargs passed: ['log_to_file']
"

When I add the log_to_file. Has something broken this argument or am I implementing it incorrectly?
I just installed the library one week ago so my version of autogluon should be up to date.

![image](https://github.com/autogluon/autogluon/assets/77838167/bf2ce8c4-b76c-46fa-a00e-c14562dd708e)
![image](https://github.com/autogluon/autogluon/assets/77838167/8f8aabe3-5cd4-4a22-85f1-48390a6f8b54)

Thanks for your work on AutoGluon guys.
