### ISSUE TITLE
[BUG] AutoGluon basic installation failing on Google Collab

### ISSUE THREAD

**Issue by greenersharp** [autogluon/autogluon#1695] opened 2022-05-03 19:06 UTC
- [ X] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

Steps to reproduce:
Start collab notebook with GPU, then:

``!pip3 install -U pip ``
``!pip3 install -U setuptools wheel ``
``!pip3 install autogluon``

after installation, try to import TextPredictor:
``from autogluon.text import TextPredictor``

the result is an ImportError:

`ImportError                               Traceback (most recent call last)
[<ipython-input-2-773ba8fa46a4>](https://localhost:8080/#) in <module>()
----> 1 from autogluon.text import TextPredictor

15 frames
[/usr/local/lib/python3.7/dist-packages/torchtext/data/datasets_utils.py](https://localhost:8080/#) in <module>()
     10 )
     11 from torch.utils.data import functional_datapipe, IterDataPipe
---> 12 from torch.utils.data.datapipes.utils.common import StreamWrapper
     13 import codecs
     14 try:

ImportError: cannot import name 'StreamWrapper' from 'torch.utils.data.datapipes.utils.common' (/usr/local/lib/python3.7/dist-packages/torch/utils/data/datapipes/utils/common.py)

---------------------------------------------------------------------------`

**Comment by sxjscience** [comment] 2022-05-04 04:32
I can confirm the error. Actually, it seems to be related to some recently upgraded packages. Investigating the root cause.

**Comment by sxjscience** [comment] 2022-05-04 05:02
@greenersharp It's certainly due to some version issues. I used the following version combination and can successfully install the package:

```python3
!pip3 install -U pip
!pip3 install -U setuptools wheel
!pip3 install autogluon.core --pre --upgrade
!pip3 install autogluon.text --pre --upgrade
!pip3 install torchtext==0.11.2 --upgrade
!pip3 install pytorch-lightning>=1.6.0 --upgrade
```

**Comment by greenersharp** [comment] 2022-05-04 13:39
> @greenersharp It's certainly due to some version issues. I used the following version combination and can successfully install the package and import TextPredictor
> 
> ```python
> !pip3 install -U pip
> !pip3 install -U setuptools wheel
> !pip3 install autogluon.core --pre --upgrade
> !pip3 install autogluon.text --pre --upgrade
> !pip3 install torchtext==0.11.2 --upgrade
> !pip3 install pytorch-lightning>=1.6.0 --upgrade
> ```

I tried this today and got the following error when trying to import TextPredictor:



/usr/local/lib/python3.7/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
[<ipython-input-4-773ba8fa46a4>](https://localhost:8080/#) in <module>()
----> 1 from autogluon.text import TextPredictor

26 frames
[/usr/local/lib/python3.7/dist-packages/tensorflow/core/framework/resource_handle_pb2.py](https://localhost:8080/#) in <module>()
    148   ,
    149   'DESCRIPTOR' : _RESOURCEHANDLEPROTO,
--> 150   '__module__' : 'tensorflow.core.framework.resource_handle_pb2'
    151   # @@protoc_insertion_point(class_scope:tensorflow.ResourceHandleProto)
    152   })

**Comment by rxjx** [comment] 2022-05-04 17:22
The workaround seems to work for me but not if I want to use 0.4.0 which is what I'd prefer to use.

**Comment by greenersharp** [comment] 2022-05-04 18:11
strange, not working for me.  like in my screenshot, I run the two cells and hit the error.

**Comment by rxjx** [comment] 2022-05-04 18:25
OK, I was able to reproduce your error. Try "disconnect and delete runtime", then. the workaround, then a restart. You error should go away, at least it did for me.

**Comment by sxjscience** [comment] 2022-05-04 18:26
I'm investigating the root-cause. It is currently not clear to me. May be related some intrinsic upgrade in colab.

**Comment by sxjscience** [comment] 2022-05-04 18:32
@rxjx @greenersharp I investigated again and feel that the root cause is `pip3 install -U pip`.

I tried the following and it will work without any issues. I guess we should not upgrade pip and just rely on the pip in Colab for doing installation:

```
!pip3 install autogluon.core
!pip3 install autogluon.features
!pip3 install autogluon.text
``` 

If that's the case, this is not actually a bug but it's due to inappropriate usage of Colab.

**Comment by greenersharp** [comment] 2022-05-04 18:47
I can confirm its now working when omitting `pip3 install -U pip` from the installation steps.

Thank you

**Comment by Innixma** [comment] 2022-05-04 21:06
Reopening as I think this requires a deeper dive to understand why this error is occurring.

**Comment by sxjscience** [comment] 2022-05-04 21:10
@Innixma I think it is because `pip3 install -U pip` may change the pip in Colab. I think this is the root-cause. We should not touch the pip in Colab.

**Comment by Innixma** [comment] 2022-05-04 21:16
> @Innixma I think it is because `pip3 install -U pip` may change the pip in Colab. I think this is the root-cause. We should not touch the pip in Colab.

I understand this, but that doesn't explain why this suddenly started happening, if it is happening outside of Colab, or if we need to update our install instructions which currently includes the pip upgrade.

**Comment by sxjscience** [comment] 2022-05-04 21:23
I actually tried adding `-U` and it also works in Colab. I guess it's not happening outside of Colab but we may take a look.

```python3
!pip3 install -U autogluon.core
!pip3 install -U autogluon.features
!pip3 install -U autogluon.text

from autogluon.text import TextPredictor
```

It's likely due to some internal upgrade of Google Colab.

**Comment by yinweisu** [comment] 2022-05-04 23:10
Did some dig into this issue:

The fundamental issue is that a fresh colab gpu env has `torch==1.11` and `torchtext==0.12.0`. The installation of `autogluon` only updates `torch` to 1.10.2 while `torchtext` remains to be 0.12.0 because `torchtext` is not part of our dependency. However, the fact that `torchtext` exists made `pytorch_lightning`, which is our dependency, to do a version check: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/imports.py#L120-L121. So  `_compare_version`  actually imports `torchtext` and `torchtext==0.12.0` is not compatible with `torch==1.10.2` because the `import from torch.utils.data.datapipes.utils.common import StreamWrapper` is not available.

**Comment by sxjscience** [comment] 2022-05-05 22:03
I still think the root-cause is `pip3 install -U pip`. I guess it is causing some problems in version detection. @yinweisu Are you able to reproduce the error locally?

**Comment by yinweisu** [comment] 2022-05-05 22:16
Local env doesn't have this issue because there's no torchtext pre-installed. Torchtext is the one that's causing problem.

It fails even when I do not do `pip3 install -U pip`: https://colab.research.google.com/drive/1kNwaW3OOsrxSN02WxzqI5LOa4QHLbROH?usp=sharing
And you can see this after `pip3 install autogluon`:
`torchtext 0.12.0 requires torch==1.11.0, but you have torch 1.10.2 which is incompatible.`

The explanation in my previous comment should be correct.

**Comment by sxjscience** [comment] 2022-05-05 22:35
Yeah, it makes sense. I just see that torchtext is a dependency of pytorch lightning https://github.com/PyTorchLightning/pytorch-lightning/blob/bb51e2a55baa851da402bf0e6786b32e141147f8/requirements/extra.txt#L4 and I guess it will be installed when we install pytorch lightning.

Also, why won't the following two commands trigger error?
```
!pip3 install autogluon.core
!pip3 install autogluon.features
!pip3 install autogluon.text
```

Install with `-U`.

```
!pip3 install -U autogluon.core
!pip3 install -U autogluon.features
!pip3 install -U autogluon.text
```

**Comment by yinweisu** [comment] 2022-05-05 22:47
Yes. I had a look at their dependency too. Torchtext won't be installed because we specified `pytorch_lightning` as our dependency instead of `pytorch_lightning[extra]`

However, even we put [extra](we should not do this if we don't need the extra dependency) this problem won't be solved because PL didn't upper cap torchtext version. The problem here is that nothing is forcing torchtext to match torch version.

As of why installation of individual module(core, features, text) works is that the torch dependency is actually specified by tabular: https://github.com/awslabs/autogluon/blob/master/tabular/setup.py#L42
Hence, the code you provided didn't update torch and torchtext is working correctly with the default torch version :).

If you install tabular along with `tabular[all]`, it will not work

**Comment by sxjscience** [comment] 2022-05-06 01:11
In that case, a simple fix is to add a version cap in text about torchtext. I feel that we can do it in 0.4.1.

**Comment by Innixma** [comment] 2022-05-06 01:39
@sxjscience Except we don't use torchtext in AutoGluon, therefore we shouldn't install it. Thus we can't control its version cap, and therefore we can't fix on our end. The only way to fix would be to needlessly depend on torchtext despite never using it in AutoGluon, simply to cap its version range, which would be obnoxious. If you'd like to discuss further I'm happy to chat directly offline as to what is happening.

**Comment by sxjscience** [comment] 2022-05-06 01:42
That also makes sense. Another solution is actually not to version cap torch but provide instructions in telling user which version to use.

**Comment by ddelange** [comment] 2022-05-30 08:12
> Did some dig into this issue:
> 
> The fundamental issue is that a fresh colab gpu env has `torch==1.11` and `torchtext==0.12.0`. The installation of `autogluon` only updates `torch` to 1.10.2 while `torchtext` remains to be 0.12.0 because `torchtext` is not part of our dependency. However, the fact that `torchtext` exists made `pytorch_lightning`, which is our dependency, to do a version check: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/utilities/imports.py#L120-L121. So `_compare_version` actually imports `torchtext` and `torchtext==0.12.0` is not compatible with `torch==1.10.2` because the `import from torch.utils.data.datapipes.utils.common import StreamWrapper` is not available.

imo torch is introducing [dephell](https://medium.com/knerd/the-nine-circles-of-python-dependency-hell-481d53e3e025) and this is not an issue with autogluon:
- if torchtext only works with specific versions of torch, torchtext should have that compatibility matrix transferred to their `install_requires`.
- if importing `autogluon.text.TextPredictor` causes an import of `torchtext` (ref PR description), torch should have (a proper version of) torchtext in their `install_requires`.

neither is the case:
```console
$ pipgrip --tree 'torch<1.11' torchtext
torch<1.11 (1.10.2)
└── typing-extensions (4.2.0)
torchtext (0.12.0)
├── numpy (1.22.4)
├── requests (2.27.1)
│   ├── certifi>=2017.4.17 (2022.5.18.1)
│   ├── charset-normalizer~=2.0.0 (2.0.12)
│   ├── idna<4,>=2.5 (3.3)
│   └── urllib3<1.27,>=1.21.1 (1.26.9)
├── torch (1.10.2)  # here should be `torch~=1.11.0` or similar forcing pip to choose an older torchtext version
│   └── typing-extensions (4.2.0)
└── tqdm (4.64.0)
```

a user should expect `pip install 'torch<1.11' torchtext` to result in a working set (as pip has a resolver). So running a simple `pip install autogluon.text` in this fresh colab env should result in pip throwing a warning `torchtext requires torch version ... but you'll have torch ... installed`, which it doesn't because torchtext doesn't pin torch.

**Comment by yinweisu** [comment] 2023-02-02 19:46
Mark as resolved as `text` module is being deprecated and just tested AG multimodal 0.6.2 on colab. This issue doesn't exist anymore

**Closed by yinweisu** 2023-02-02 19:46 UTC
Labels: bug, module: multimodal, env: colab, priority: 0
