### ISSUE TITLE
Wheel for Python 3.11

### ISSUE THREAD

**Issue by amueller** [autogluon/autogluon#3213] opened 2023-05-13 00:00 UTC
Hi.
Is there a plan to release for Python3.11? Now that Python3.12 is around the corner...
Also, is it possible to bump the scipy dependency? I tried installing the pre-release on 3.11, but the pinning of scipy means that it tries to install scipy from source (as there's no wheels old enough to support your requirements). SciPy <=1.5 was released in 2019 for Python<=3.8.

**Comment by Innixma** [comment] 2023-05-15 18:15
Hey @amueller,

Regarding scipy version, we are using [the following version range](https://github.com/autogluon/autogluon/blob/master/core/src/autogluon/core/_setup_utils.py#LL26C5-L26C52):

```
'scipy': '>=1.5.4,<1.12',  # "<{N+2}" upper cap
```

You may want to check that you are installing the latest v0.7 release of AutoGluon.

Regarding Python 3.11, we are looking to support this in an upcoming release, but not in the v0.8 release as there are still some of our dependencies that have yet to add support for Python 3.11. #2687

**Comment by Innixma** [comment] 2023-05-15 18:18
Resolving as a duplicate of #2687

**Closed by Innixma** 2023-05-15 18:18 UTC
Labels: duplicate

**Comment by amueller** [comment] 2023-05-15 22:05
Oh, I must have misread the "<=", I'll go back and see what the issue was that I was running into. Thank you!

**Comment by Innixma** [comment] 2023-05-16 16:22
@amueller I don't think you mis-read it, I think instead you installed a very old version of AutoGluon pre-release (which is our bad), since only the very old versions claim support for all Python versions (we didn't have Python version range limits back then)

For example:

`pip install --pre autogluon`

-> autogluon==0.8.0b20230515  # not compatible as it doesn't support Python 3.11, so it won't install this
-> autogluon==0.0.10b20200505  # would install this because we didn't specify python version limits, the install will fail.

**Comment by amueller** [comment] 2023-05-18 16:36
Yes, that makes sense!
