### ISSUE TITLE
Not able install Autogluon in my windows system. It is not able to find numpy==1.21.3 

### ISSUE THREAD

**Issue by rahulhiware** [autogluon/autogluon#3919] opened 2024-02-14 04:08 UTC
Hi,
I am not able to install Autogluon  in my windows 10 system. 
I am using "pip install autogluon**" command in command prompt. I have python 3.11.0 install and can't downgrade it due to other dependencies
.
While installation giving below error. I tried manually installing numpy==1.21.3 but I guess it is not supporting python 3.11.0.
Please help.

ERROR: Could not find a version that satisfies the requirement numpy==1.21.3 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0rc1, 1.25.0, 1.25.1, 1.25.2, 1.26.0b1, 1.26.0rc1, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4)
      ERROR: No matching distribution found for numpy==1.21.3

Thanks

**Comment by shchur** [comment] 2024-02-14 08:32
Hi @rahulhiware, there is a problem with installation on Windows with Python 3.11 caused by ray (see #3807). Our current recommendation is to create a virtual environment with Python 3.10 (e.g., using conda or virtualenv) and install AutoGluon there. We are currently working on a fix that should address this problem.

I am closing this issue for now since it's a duplicate of #3807.

**Closed by shchur** 2024-02-14 08:32 UTC
