### ISSUE TITLE
[BUG] TimeSeriesPredictor leaderboard EOFError

### ISSUE THREAD

**Issue by Ai-Ya-Ya** [autogluon/autogluon#4150] opened 2024-04-30 01:57 UTC
**Bug Report Checklist**

- [X] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [X] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Calling `TimeSeriesPredictor.leaderboard(data)` results in `EOFError: Ran out of input`. This is very strange, as `predictor.leaderboard` was working just a few days earlier, on the exact same version. I made no changes to my code since then. Full stack trace below. 

```
Traceback (most recent call last):
  File "/fs/cml-projects/teamgahsp/gahsp/moco_crime_model.py", line 67, in <module>
    predictor.leaderboard(test_data)
  File "/fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/predictor.py", line 1232, in leaderboard
    leaderboard = self._learner.leaderboard(data, use_cache=use_cache)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/learner.py", line 286, in leaderboard
    return self.load_trainer().leaderboard(data, use_cache=use_cache)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 779, in leaderboard
    model_predictions, pred_time_dict = self.get_model_pred_dict(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 1159, in get_model_pred_dict
    model_pred_dict, pred_time_dict_marginal = self._get_cached_pred_dicts(dataset_hash)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 1231, in _get_cached_pred_dicts
    cached_predictions = load_pkl.load(str(self._cached_predictions_path))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/common/loaders/load_pkl.py", line 44, in load
    object = pickle.load(fin)
             ^^^^^^^^^^^^^^^^
EOFError: Ran out of input
```

**Expected behavior**
I expected an actual leaderboard. 

**To Reproduce**
Training code pasted below. Data source [here](https://docs.google.com/spreadsheets/d/1VJl7-yHNhByBCt1-ZA7o_bpOC7WzqqJx/edit?usp=sharing&ouid=111611764028797479108&rtpof=true&sd=true). 

```python
import pandas as pd
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
import requests

data = pd.read_excel("data/moco_income_and_crimes.xlsx")
data = data[data['Start_Date_Time'] != '']
data.dropna(how='all')
data = data.rename(columns={'FID_moco_crime_grid' : 'grid', 'Start_Date_Time' : 'time', 'Income' : 'income', 'Crime_Name2' : 'category'})

columns_that_matter = ['grid', 'time', 'income']
data = data.rename(columns={'FID_moco_crime_grid' : 'grid', 'Start_Date_Time' : 'time'})
data = data[columns_that_matter]
data['time'] = pd.to_datetime(data['time'])
data.dropna(inplace=True)

data['weighted_crime'] = 1.0
data1 = pd.DataFrame(data['grid'].unique(), columns=['grid'])
data1['time'] = pd.to_datetime(data['time'].min())
data1['weighted_crime'] = 0.0
data1 = pd.merge(data1, data[['income', 'grid']], on='grid', how='inner')
data = pd.concat([data, data1])
data1 = pd.DataFrame(data['grid'].unique(), columns=['grid'])
data1['time'] = pd.to_datetime(data['time'].max())
data1['weighted_crime'] = 0.0
data1 = pd.merge(data1, data[['income', 'grid']], on='grid', how='inner')
data = pd.concat([data, data1])
data1 = data.groupby(['grid', 'time'])['weighted_crime'].sum().reset_index()
data1['income'] = data.groupby(['grid', 'time'])['income'].mean().reset_index()['income']
data = data1

train_data = TimeSeriesDataFrame.from_data_frame(data, id_column='grid', timestamp_column='time')
train_data = train_data.convert_frequency(freq='D')
train_data['weighted_crime'] = train_data.fill_missing_values(method='constant')['weighted_crime']
train_data['income'] = train_data.fill_missing_values()['income']

from pandas.tseries.holiday import USFederalHolidayCalendar

WEEKEND_INDICES = [5, 6]
timestamps = train_data.index.get_level_values('timestamp')
train_data["weekend"] = timestamps.weekday.isin(WEEKEND_INDICES).astype(float)
holidays = USFederalHolidayCalendar().holidays(start='2015-01-01', end='2023-01-31').to_pydatetime()
train_data['holiday'] = timestamps.isin(holidays).astype(float)

prediction_length = 360
train_data, test_data = train_data.train_test_split(prediction_length)

from autogluon.timeseries.utils.forecast import get_forecast_horizon_index_ts_dataframe

future_index = get_forecast_horizon_index_ts_dataframe(test_data, prediction_length=prediction_length)
future_timestamps = future_index.get_level_values('timestamp')
known_covariates = pd.DataFrame(index=future_index)
known_covariates['weekend'] = future_timestamps.weekday.isin(WEEKEND_INDICES).astype(float)
known_covariates['holiday'] = future_timestamps.isin(holidays).astype(float)

predictor = TimeSeriesPredictor(
    prediction_length = prediction_length, 
    path = './models/moco_total_crimes_year/', 
    target = 'weighted_crime',
    known_covariates_names=['income', 'weekend', 'holiday'], 
    eval_metric = 'mean_wQuantileLoss',
)
# predictor.fit(train_data, presets='fast_training')
# predictor.fit(train_data, presets='high_quality', excluded_model_types=['DirectTabular', 'DeepAR', 'TemporalFusionTransformer', 'PatchTST'])
# predictor.fit(train_data, presets='high_quality', excluded_model_types=['DirectTabular', 'DeepAR'])
predictor.fit(train_data, presets='best_quality', excluded_model_types=['DirectTabular', 'Chronos'])
print(predictor.leaderboard(test_data))
print('\n\n\n')
```

I encounter the same issue when loading the model from file. Cross-validation code below. 

```python
import pandas as pd
import numpy as np
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
import requests
from pandas.tseries.holiday import USFederalHolidayCalendar

predictor = TimeSeriesPredictor.load('./models/moco_total_crimes_year')

df = pd.read_excel("data/moco_income_and_crimes.xlsx")
df = df[df['Start_Date_Time'] != '']
# df['Start_Date_Time'] = df['Start_Date_Time'].str[:10]
# df['target'] = 1
# df['Location'] = df['Location'].str[1:-1]
df.dropna(how='all')
# df = df[df.columns.intersection(['Start_Date_Time','target','Location','Block Address','City','State','Zip Code'])]
# df[~df[['Block Address','City','State','Zip Code']].isna().any(axis=1)].to_csv('moco_crime_clean_address.csv')
# df[~(df['Location'] == '0.0, 0.0')].to_csv('moco_crime_clean_latlong.csv')
# df['Block Address'] = df['Block Address'].str.replace('BLK', '')
# df[~df[['Block Address','City','State','Zip Code']].isna().any(axis=1) & (df['Location'] == '0.0, 0.0')].to_csv('moco_crime_no_latlong.csv')
# df[~(df['Location'] == '0.0, 0.0') & df[['Block Address','City','State','Zip Code']].isna().any(axis=1)].to_csv('moco_crime_no_address.csv')
# dataset 1: street address, no lat/long
# dataset 2: lat/long, no street address
# df[~df[['Block Address','City','State','Zip Code']].isna().any(axis=1) & ~(df['Location'] == '0.0, 0.0')].to_csv('moco_crime_clean_everything.csv')
df = df.rename(columns={'FID_moco_crime_grid' : 'grid', 'Start_Date_Time' : 'time', 'Income' : 'income'})

df = df.rename(columns={'Crime_Name2' : 'category'})
columns_that_matter = ['grid', 'time', 'category', 'income']
df = df.rename(columns={'FID_moco_grid' : 'grid', 'Start_Date_Time' : 'time'})
df = df[columns_that_matter]
df['time'] = pd.to_datetime(df['time'])
df.dropna(inplace=True)

for category in df.category.unique():
    data = df[df['category'] == category]

    data['weighted_crime'] = 1.0
    # display(data)
    data1 = pd.DataFrame(data['grid'].unique(), columns=['grid'])
    data1['time'] = pd.to_datetime(data['time'].min())
    data1['weighted_crime'] = 0.0
    data1 = pd.merge(data1, data[['income', 'grid']], on='grid', how='inner')
    # display(data1)
    data = pd.concat([data, data1])
    data1 = pd.DataFrame(data['grid'].unique(), columns=['grid'])
    data1['time'] = pd.to_datetime(data['time'].max())
    data1['weighted_crime'] = 0.0
    data1 = pd.merge(data1, data[['income', 'grid']], on='grid', how='inner')
    # display(data1)
    data = pd.concat([data, data1])

    data1 = data.groupby(['grid', 'time'])['weighted_crime'].sum().reset_index()
    data1['income'] = data.groupby(['grid', 'time'])['income'].mean().reset_index()['income']
    data = data1

    train_data = TimeSeriesDataFrame.from_data_frame(data, id_column='grid', timestamp_column='time')
    train_data = train_data.convert_frequency(freq='D')
    train_data['weighted_crime'] = train_data.fill_missing_values(method='constant')['weighted_crime']
    train_data['income'] = train_data.fill_missing_values()['income']

    WEEKEND_INDICES = [5, 6]
    timestamps = train_data.index.get_level_values('timestamp')
    train_data["weekend"] = timestamps.weekday.isin(WEEKEND_INDICES).astype(float)
    
    holidays = USFederalHolidayCalendar().holidays(start='2015-01-01', end='2023-01-31').to_pydatetime()
    train_data['holiday'] = timestamps.isin(holidays).astype(float)

    prediction_length = 360
    train_data, test_data = train_data.train_test_split(prediction_length)

    print(f'Cross-validation scores for crime category {category}:\n')
    print(predictor.leaderboard(test_data))
    print('\n\n')
```

**Screenshots / Logs**
Stack trace pasted above. 

**Installed Versions**

<details>

```python
INSTALLED VERSIONS
------------------
date                   : 2024-04-29
time                   : 21:56:53.212048
python                 : 3.11.2.final.0
OS                     : Linux
OS-release             : 4.18.0-513.24.1.el8_9.x86_64
Version                : #1 SMP Thu Mar 14 14:20:09 EDT 2024
machine                : x86_64
processor              : x86_64
num_cores              : 32
cpu_ram_mb             : 257274.11328125
cuda version           : 12.550.54.14
num_gpus               : 1
gpu_ram_mb             : [16101]
avail_disk_size_mb     : 143326

accelerate             : 0.21.0
autogluon              : 1.1.0
autogluon.common       : 1.1.0
autogluon.core         : 1.1.0
autogluon.features     : 1.1.0
autogluon.multimodal   : 1.1.0
autogluon.tabular      : 1.1.0
autogluon.timeseries   : 1.1.0
boto3                  : 1.34.91
catboost               : 1.2.5
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.14
gluonts                : 0.14.3
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.3
joblib                 : 1.4.0
jsonschema             : 4.21.1
lightgbm               : 4.3.0
lightning              : 2.2.3
matplotlib             : 3.8.4
mlforecast             : 0.10.0
networkx               : 3.3
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.26.4
nvidia-ml-py3          : None
omegaconf              : 2.3.0
onnxruntime-gpu        : None
openmim                : 0.3.7
optimum                : None
optimum-intel          : None
orjson                 : 3.9.15
pandas                 : 2.2.2
pdf2image              : 1.17.0
Pillow                 : 10.3.0
psutil                 : 5.9.8
pytesseract            : 0.3.10
pytorch-lightning      : 2.2.2
pytorch-metric-learning: 2.3.0
ray                    : 2.10.0
requests               : 2.31.0
scikit-image           : 0.20.0
scikit-learn           : 1.4.0
scikit-learn-intelex   : None
scipy                  : 1.12.0
seqeval                : 1.2.2
setuptools             : 69.5.1
skl2onnx               : None
statsforecast          : 1.4.0
tabpfn                 : None
tensorboard            : 2.16.2
text-unidecode         : 1.3
timm                   : 0.9.16
torch                  : 2.1.2.post300
torchmetrics           : 1.2.1
torchvision            : 0.16.1+b88453f
tqdm                   : 4.66.2
transformers           : 4.40.0
utilsforecast          : 0.1.7
vowpalwabbit           : None
xgboost                : 2.0.3
```

</details>

**Comment by Ai-Ya-Ya** [comment] 2024-04-30 17:34
This error occurs when trying to load any model. `predictor.load` will work fine, but any other methods called to predictor, such as `predictor.predict()` will not.

**Comment by Ai-Ya-Ya** [comment] 2024-04-30 17:35
Here is a more verbose stack trace. 

```
---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
Cell In[12], line 1
----> 1 predictor.predict(train_data, known_covariates=test_data[['income', 'weekend', 'holiday']], model='WeightedEnsemble')

File /fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/predictor.py:845, in TimeSeriesPredictor.predict(self, data, known_covariates, model, use_cache, random_seed)
    843 if known_covariates is not None:
    844     known_covariates = self._to_data_frame(known_covariates)
--> 845 predictions = self._learner.predict(
    846     data,
    847     known_covariates=known_covariates,
    848     model=model,
    849     use_cache=use_cache,
    850     random_seed=random_seed,
    851 )
    852 return predictions.reindex(original_item_id_order, level=ITEMID)

File /fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/learner.py:185, in TimeSeriesLearner.predict(self, data, known_covariates, model, use_cache, random_seed, **kwargs)
    183 known_covariates = self.feature_generator.transform_future_known_covariates(known_covariates)
    184 known_covariates = self._align_covariates_with_forecast_index(known_covariates=known_covariates, data=data)
--> 185 return self.load_trainer().predict(
    186     data=data,
    187     known_covariates=known_covariates,
    188     model=model,
    189     use_cache=use_cache,
    190     random_seed=random_seed,
    191     **kwargs,
    192 )

File /fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/trainer/abstract_trainer.py:892, in AbstractTimeSeriesTrainer.predict(self, data, known_covariates, model, use_cache, random_seed, **kwargs)
    882 def predict(
    883     self,
    884     data: TimeSeriesDataFrame,
   (...)
    889     **kwargs,
    890 ) -> TimeSeriesDataFrame:
    891     model_name = self._get_model_for_prediction(model)
--> 892     model_pred_dict = self.get_model_pred_dict(
    893         model_names=[model_name],
    894         data=data,
    895         known_covariates=known_covariates,
    896         use_cache=use_cache,
    897         random_seed=random_seed,
    898     )
    899     return model_pred_dict[model_name]

File /fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/trainer/abstract_trainer.py:1159, in AbstractTimeSeriesTrainer.get_model_pred_dict(self, model_names, data, known_covariates, record_pred_time, raise_exception_if_failed, use_cache, random_seed)
   1157 if self.cache_predictions and use_cache:
   1158     dataset_hash = self._compute_dataset_hash(data=data, known_covariates=known_covariates)
-> 1159     model_pred_dict, pred_time_dict_marginal = self._get_cached_pred_dicts(dataset_hash)
   1160 else:
   1161     model_pred_dict = {}

File /fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/timeseries/trainer/abstract_trainer.py:1231, in AbstractTimeSeriesTrainer._get_cached_pred_dicts(self, dataset_hash)
   1229 """Load cached predictions for given dataset_hash from disk, if possible. Otherwise returns empty dicts."""
   1230 if self._cached_predictions_path.exists():
-> 1231     cached_predictions = load_pkl.load(str(self._cached_predictions_path))
   1232     if dataset_hash in cached_predictions:
   1233         model_pred_dict = cached_predictions[dataset_hash]["model_pred_dict"]

File /fs/cml-projects/teamgahsp/miniforge3/envs/new_env/lib/python3.11/site-packages/autogluon/common/loaders/load_pkl.py:44, in load(path, format, verbose, **kwargs)
     42 if compression_fn in compression_fn_map:
     43     with compression_fn_map[compression_fn]["open"](validated_path, "rb", **compression_fn_kwargs) as fin:
---> 44         object = pickle.load(fin)
     45 else:
     46     raise ValueError(
     47         f"compression_fn={compression_fn} or compression_fn_kwargs={compression_fn_kwargs} are not valid."
     48         f" Valid function values: {compression_fn_map.keys()}"
     49     )

EOFError: Ran out of input
```

**Comment by Ai-Ya-Ya** [comment] 2024-04-30 18:05
I added a line `print(fin)` right before `object = pickle.load(fin)`. It produced the following output: 

```
<_io.BufferedReader name='./models/moco_total_crimes_year/learner.pkl'>
<_io.BufferedReader name='./models/moco_total_crimes_year/predictor.pkl'>

<_io.BufferedReader name='./models/moco_total_crimes_year/models/trainer.pkl'>
<_io.BufferedReader name='models/moco_total_crimes_year/models/cached_predictions.pkl'>
```

The error seems to be in the last line, which for some reason does not include the `./` in the path, even though I clearly specified `./` in my path in code.

**Comment by Ai-Ya-Ya** [comment] 2024-05-01 02:35
Doing a few more runs, it's clear that every other path has `./` included except for the path to `cached_predictions.pkl`.

**Comment by shchur** [comment] 2024-05-04 18:03
Hi @Ai-Ya-Ya, thanks a lot for such a detailed description of the problem! I tried running the code on my machine but unfortunately wasn't able to reproduce the error. I'm not 100% sure at this point, but it's possible that the error was caused by the fact that multiple different predictors were trained & saved in the same directory `./models/moco_total_crimes_year/`. Can you please try deleting the existing folder (or providing a different `path` to the `TimeSeriesPredictor`) and check if the problem persists?

If changing the save path does not fix the issue, can you please also share the log produced by `predictor.fit()`?

**Comment by Ai-Ya-Ya** [comment] 2024-05-06 22:22
Deleting `cached_predictions.pkl` fixed the error. For completeness, here is the training log. 

```
Beginning AutoGluon training...
AutoGluon will save models to './models/moco_total_crimes_year/'
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.11.2
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Mar 14 14:20:09 EDT 2024
CPU Count:          32
GPU Count:          1
Memory Avail:       242.87 GB / 251.24 GB (96.7%)
Disk Space Avail:   143.00 GB / 199.86 GB (71.5%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'excluded_model_types': ['DirectTabular'],
 'hyperparameters': 'default',
 'known_covariates_names': ['income', 'weekend', 'holiday'],
 'num_val_windows': 2,
 'prediction_length': 360,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'weighted_crime',
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 14362998 rows, 6942 time series. Median time series length is 2069 (min=2069, max=2069). 

Provided data contains following columns:
	target: 'weighted_crime'
	known_covariates:
		categorical:        []
		continuous (float): ['income', 'weekend', 'holiday']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-04-26 01:57:53
Excluded model types: ['DirectTabular']
	Found 'DirectTabular' model in `hyperparameters`, but 'DirectTabular' is present in `excluded_model_types` and will be removed.
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'Chronos[base]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST']
Training timeseries model SeasonalNaive. 
	-12.0257      = Validation score (-WQL)
	25.76   s     = Training runtime
	4.61    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. 
	-16.2404      = Validation score (-WQL)
	629.90  s     = Training runtime
	70.54   s     = Validation (prediction) runtime
Training timeseries model CrostonSBA. 
	-1.5597       = Validation score (-WQL)
	36.10   s     = Training runtime
	4.16    s     = Validation (prediction) runtime
Training timeseries model NPTS. 
	-0.9912       = Validation score (-WQL)
	1268.46 s     = Training runtime
	1552.44 s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta. 
	-3.5623       = Validation score (-WQL)
	164.15  s     = Training runtime
	202.86  s     = Validation (prediction) runtime
Training timeseries model AutoETS. 
	-2.5420       = Validation score (-WQL)
	139.51  s     = Training runtime
	147.68  s     = Validation (prediction) runtime
Training timeseries model AutoARIMA. 
	-2.6293       = Validation score (-WQL)
	200.54  s     = Training runtime
	229.51  s     = Validation (prediction) runtime
Training timeseries model Chronos[base]. 
	-1.1172       = Validation score (-WQL)
	13480.34 s    = Training runtime
	13490.92 s    = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. 
	-0.9863       = Validation score (-WQL)
	702.91  s     = Training runtime
	9.27    s     = Validation (prediction) runtime
Training timeseries model DeepAR. 
	-1.0003       = Validation score (-WQL)
	482.55  s     = Training runtime
	170.52  s     = Validation (prediction) runtime
Training timeseries model PatchTST. 
	-1.0007       = Validation score (-WQL)
	171.35  s     = Training runtime
	58.21   s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'DeepAR': 0.36, 'TemporalFusionTransformer': 0.64}
	-0.9810       = Validation score (-WQL)
	1360.96 s     = Training runtime
	179.79  s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'Chronos[base]', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'WeightedEnsemble']
Total runtime: 34629.08 s
Best model: WeightedEnsemble
Best model score: -0.9810
Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).
Beginning AutoGluon training...
AutoGluon will save models to './models/moco_total_crimes_year/'
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.11.2
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Mar 14 14:20:09 EDT 2024
CPU Count:          32
GPU Count:          1
Memory Avail:       223.71 GB / 251.24 GB (89.0%)
Disk Space Avail:   139.97 GB / 199.86 GB (70.0%)
===================================================
Setting presets to: best_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': WQL,
 'excluded_model_types': ['DirectTabular', 'Chronos'],
 'hyperparameters': 'default',
 'known_covariates_names': ['income', 'weekend', 'holiday'],
 'num_val_windows': 2,
 'prediction_length': 360,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'weighted_crime',
 'verbosity': 2}

Inferred time series frequency: 'D'
Provided train_data has 14362998 rows, 6942 time series. Median time series length is 2069 (min=2069, max=2069). 

Provided data contains following columns:
	target: 'weighted_crime'
	known_covariates:
		categorical:        []
		continuous (float): ['income', 'weekend', 'holiday']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'WQL'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-04-29 18:35:27
Excluded model types: ['DirectTabular', 'Chronos']
	Found 'DirectTabular' model in `hyperparameters`, but 'DirectTabular' is present in `excluded_model_types` and will be removed.
	Found 'Chronos' model in `hyperparameters`, but 'Chronos' is present in `excluded_model_types` and will be removed.
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST']
Training timeseries model SeasonalNaive. 
	-12.0309      = Validation score (-WQL)
	24.19   s     = Training runtime
	4.66    s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular. 
	-16.2699      = Validation score (-WQL)
	897.24  s     = Training runtime
	76.29   s     = Validation (prediction) runtime
Training timeseries model CrostonSBA. 
	-1.5599       = Validation score (-WQL)
	37.87   s     = Training runtime
	3.72    s     = Validation (prediction) runtime
Training timeseries model NPTS. 
	-0.9914       = Validation score (-WQL)
	1257.55 s     = Training runtime
	1533.80 s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta. 
	-3.5636       = Validation score (-WQL)
	163.58  s     = Training runtime
	199.16  s     = Validation (prediction) runtime
Training timeseries model AutoETS. 
	-2.5428       = Validation score (-WQL)
	145.37  s     = Training runtime
	153.86  s     = Validation (prediction) runtime
Training timeseries model AutoARIMA. 
	-2.6302       = Validation score (-WQL)
	206.89  s     = Training runtime
	238.38  s     = Validation (prediction) runtime
Training timeseries model TemporalFusionTransformer. 
	-0.9861       = Validation score (-WQL)
	809.46  s     = Training runtime
	9.25    s     = Validation (prediction) runtime
Training timeseries model DeepAR. 
	-1.0002       = Validation score (-WQL)
	712.14  s     = Training runtime
	168.94  s     = Validation (prediction) runtime
Training timeseries model PatchTST. 
	-1.0008       = Validation score (-WQL)
	166.02  s     = Training runtime
	59.50   s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'DeepAR': 0.36, 'TemporalFusionTransformer': 0.64}
	-0.9811       = Validation score (-WQL)
	1289.41 s     = Training runtime
	178.19  s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'RecursiveTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'TemporalFusionTransformer', 'DeepAR', 'PatchTST', 'WeightedEnsemble']
Total runtime: 8186.39 s
Best model: WeightedEnsemble
Best model score: -0.9811
Additional data provided, testing on additional data. Resulting leaderboard will be sorted according to test score (`score_test`).
```

**Comment by shchur** [comment] 2024-05-07 07:39
Thank you for confirming that the issue is resolved! Closing the issue for now

**Closed by shchur** 2024-05-07 07:39 UTC
Labels: bug: unconfirmed
