### ISSUE TITLE
Hyperparemeter Optimization for Time Series stoped working 

### ISSUE THREAD

**Issue by DiegoDVillacreses** [autogluon/autogluon#3892] opened 2024-01-29 22:24 UTC
**Describe the bug**
I carefully installed autogluon for Windows-Pip-GPU (https://auto.gluon.ai/stable/install.html). autogluon works perfecty withouth HPO (fast training to best results). When I try to HPO `PatchTST` I got this error `prediction-net-state.pt`. Which does not happen when I HPO on autogluon for CPU. I am on a Windows 11 laptop with all the last updates. Bellow I attach all the relevant information for you to check the error.

```Bash
Beginning AutoGluon training... Time limit = 7200s
AutoGluon will save models to 'autogluon-m4-hourly'
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.9.18
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.22631
CPU Count:          32
GPU Count:          1
Memory Avail:       15.75 GB / 31.69 GB (49.7%)
Disk Space Avail:   769.92 GB / 952.89 GB (80.8%)
===================================================

Fitting with arguments:
{'enable_ensemble': False,
 'eval_metric': MASE,
 'hyperparameter_tune_kwargs': {'num_trials': 2,
                                'scheduler': 'local',
                                'searcher': 'random'},
 'hyperparameters': {'PatchTST': {'nhead': Categorical[2, 4]}},
 'known_covariates_names': [],
 'num_val_windows': 2,
 'prediction_length': 48,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'target': 'target',
 'time_limit': 7200,
 'verbosity': 2}

Inferred time series frequency: 'H'
Provided train_data has 148060 rows, 200 time series. Median time series length is 700 (min=700, max=960).

Provided dataset contains following columns:
        target:           'target'

AutoGluon will gauge predictive performance using evaluation metric: 'MASE'
        This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-01-29 17:14:49
Models that will be trained: ['PatchTST']
Hyperparameter tuning model PatchTST. Tuning model for up to 7198.9s of the 7198.9s remaining.
Traceback (most recent call last):
  File "c:\Users\diego.villacreses\OneDrive - Universidad de Las Américas\Desktop\MT\forecast_ventas\notebooks\tmp2.py", line 19, in <module>   
    predictor.fit(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\core\utils\decorators.py", line 31, in _call    
    return f(*gargs, **gkwargs)
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\predictor.py", line 681, in fit      
    self._learner.fit(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\learner.py", line 63, in fit
    return self._fit(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\learner.py", line 118, in _fit       
    self.trainer.fit(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\trainer\auto_trainer.py", line 63, in fit
    self._train_multi(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\trainer\abstract_trainer.py", line 587, in _train_multi
    model_names_trained += self.tune_model_hyperparameters(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\trainer\abstract_trainer.py", line 448, in tune_model_hyperparameters
    model_hpo = self.load_model(model_hpo_name, path=model_path, model_type=type(model))
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\trainer\abstract_trainer.py", line 170, in load_model
    return model_type.load(path=os.path.join(self.path, path), reset_paths=self.reset_paths)
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\models\multi_window\multi_window_model.py", line 225, in load
    model.most_recent_model = model.model_base_type.load(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\autogluon\timeseries\models\gluonts\abstract_gluonts.py", line 208, in load
    model.gts_predictor = PyTorchPredictor.deserialize(Path(path) / cls.gluonts_model_path)
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\gluonts\torch\model\predictor.py", line 117, in deserialize
    state_dict = torch.load(
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\torch\serialization.py", line 791, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\torch\serialization.py", line 271, in _open_file_like     
    return _open_file(name_or_buffer, mode)
  File "C:\Users\diego.villacreses\AppData\Local\miniconda3\envs\ag\lib\site-packages\torch\serialization.py", line 252, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\diego.villacreses\\notebooks\\autogluon-m4-hourly\\models\\PatchTST\\d196b_00000\\W1\\gluon_ts\\prediction-net-state.pt'
```

**To Reproduce**
```Python
import pandas as pd
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
from autogluon.common import space


df = pd.read_csv("https://autogluon.s3.amazonaws.com/datasets/timeseries/m4_hourly_subset/train.csv")
train_data = TimeSeriesDataFrame.from_data_frame(
    df,
    id_column="item_id",
    timestamp_column="timestamp"
)
predictor = TimeSeriesPredictor(
    prediction_length=48,
    path="autogluon-m4-hourly",
    target="target",
    eval_metric="MASE",
)

predictor.fit(
    train_data,
    hyperparameters={
        "PatchTST": {"nhead": space.Categorical(2, 4)},
    },
    hyperparameter_tune_kwargs={
        "num_trials": 2,
        "scheduler": "local", # local, FIFO ASHA
        "searcher": "random", # auto, bayes, random
    },
    enable_ensemble=False,
    time_limit=60*60*2,  # total training time in seconds
    num_val_windows=2,
)
print(predictor.leaderboard())
```

**Screenshots / Logs**

**Installed Versions**
```Bash
absl-py                  2.1.0
accelerate               0.21.0
aiohttp                  3.9.3
aiohttp-cors             0.7.0
aiosignal                1.3.1
aliyun-python-sdk-core   2.14.0
aliyun-python-sdk-kms    2.16.2
ansicon                  1.89.0
antlr4-python3-runtime   4.9.3
anyio                    4.2.0
arrow                    1.3.0
async-timeout            4.0.3
attrs                    23.2.0
autogluon                1.0.0
autogluon.common         1.0.0
autogluon.core           1.0.0
autogluon.features       1.0.0
autogluon.multimodal     1.0.0
autogluon.tabular        1.0.0
autogluon.timeseries     1.0.0
backoff                  2.2.1
beautifulsoup4           4.12.3
blessed                  1.20.0
blis                     0.7.11
boto3                    1.34.30
botocore                 1.34.30
cachetools               5.3.2
catalogue                2.0.10
catboost                 1.2.2
certifi                  2023.11.17
cffi                     1.16.0
charset-normalizer       3.3.2
click                    8.1.7
cloudpathlib             0.16.0
cloudpickle              3.0.0
colorama                 0.4.6
colorful                 0.5.6
confection               0.1.4
contourpy                1.2.0
crcmod                   1.7
croniter                 1.4.1
cryptography             42.0.1
cycler                   0.12.1
cymem                    2.0.8
datasets                 2.10.1
dateutils                0.6.12
deepdiff                 6.7.1
defusedxml               0.7.1
dill                     0.3.6
distlib                  0.3.8
editor                   1.6.6
et-xmlfile               1.1.0
evaluate                 0.4.1
exceptiongroup           1.2.0
fastai                   2.7.13
fastapi                  0.109.0
fastcore                 1.5.29
fastdownload             0.0.7
fastprogress             1.0.3
filelock                 3.13.1
fonttools                4.47.2
frozenlist               1.4.1
fsspec                   2023.12.2
future                   0.18.3
gdown                    5.0.1
gluonts                  0.14.3
google-api-core          2.15.0
google-auth              2.27.0
google-auth-oauthlib     1.2.0
googleapis-common-protos 1.62.0
gpustat                  1.1.1
graphviz                 0.20.1
grpcio                   1.60.0
h11                      0.14.0
huggingface-hub          0.20.3
hyperopt                 0.2.7
idna                     3.6
imageio                  2.33.1
importlib-metadata       7.0.1
importlib-resources      6.1.1
inquirer                 3.2.3
itsdangerous             2.1.2
Jinja2                   3.1.3
jinxed                   1.2.1
jmespath                 0.10.0
joblib                   1.3.2
jsonschema               4.17.3
kiwisolver               1.4.5
langcodes                3.3.0
lazy_loader              0.3
lightgbm                 4.1.0
lightning                2.0.9.post0
lightning-cloud          0.5.62
lightning-utilities      0.10.1
llvmlite                 0.41.1
Markdown                 3.5.2
markdown-it-py           3.0.0
MarkupSafe               2.1.4
matplotlib               3.8.2
mdurl                    0.1.2
mlforecast               0.10.0
model-index              0.1.11
mpmath                   1.3.0
msgpack                  1.0.7
multidict                6.0.4
multiprocess             0.70.14
murmurhash               1.0.10
networkx                 3.2.1
nlpaug                   1.1.11
nltk                     3.8.1
nptyping                 2.4.1
numba                    0.58.1
numpy                    1.24.4
nvidia-ml-py             12.535.133
nvidia-ml-py3            7.352.0
oauthlib                 3.2.2
omegaconf                2.2.3
opencensus               0.11.4
opencensus-context       0.1.3
opendatalab              0.0.10
openmim                  0.3.9
openpyxl                 3.1.2
openxlab                 0.0.34
ordered-set              4.1.0
orjson                   3.9.12
oss2                     2.17.0
packaging                23.2
pandas                   2.1.4
patsy                    0.5.6
pillow                   10.2.0
pip                      23.3.2
platformdirs             3.11.0
plotly                   5.18.0
preshed                  3.0.9
prometheus-client        0.19.0
protobuf                 4.23.4
psutil                   5.9.8
py-spy                   0.3.14
py4j                     0.10.9.7
pyarrow                  6.0.1
pyasn1                   0.5.1
pyasn1-modules           0.3.0
pycparser                2.21
pycryptodome             3.20.0
pydantic                 1.10.14
Pygments                 2.17.2
PyJWT                    2.8.0
pyparsing                3.1.1
pyrsistent               0.20.0
PySocks                  1.7.1
pytesseract              0.3.10
python-dateutil          2.8.2
python-multipart         0.0.6
pytorch-lightning        2.0.9.post0
pytorch-metric-learning  1.7.3
pytz                     2023.4
PyWavelets               1.5.0
pywin32                  306
PyYAML                   6.0.1
ray                      2.6.3
readchar                 4.0.5
regex                    2023.12.25
requests                 2.28.2
requests-oauthlib        1.3.1
responses                0.18.0
rich                     13.4.2
rsa                      4.9
runs                     1.2.2
s3transfer               0.10.0
safetensors              0.4.2
scikit-image             0.20.0
scikit-learn             1.4.0
scipy                    1.9.1
sentencepiece            0.1.99
seqeval                  1.2.2
setuptools               60.2.0
six                      1.16.0
smart-open               6.4.0
sniffio                  1.3.0
soupsieve                2.5
spacy                    3.7.2
spacy-legacy             3.0.12
spacy-loggers            1.0.5
srsly                    2.4.8
starlette                0.35.1
starsessions             1.3.0
statsforecast            1.4.0
statsmodels              0.14.1
sympy                    1.12
tabulate                 0.9.0
tenacity                 8.2.3
tensorboard              2.15.1
tensorboard-data-server  0.7.2
tensorboardX             2.6.2.2
text-unidecode           1.3
thinc                    8.2.2
threadpoolctl            3.2.0
tifffile                 2024.1.30
timm                     0.9.12
tokenizers               0.13.3
toolz                    0.12.1
torch                    2.0.1+cu118
torchmetrics             1.1.2
torchvision              0.15.2+cu118
tqdm                     4.65.2
traitlets                5.14.1
transformers             4.31.0
typer                    0.9.0
types-python-dateutil    2.8.19.20240106
typing_extensions        4.9.0
tzdata                   2023.4
urllib3                  1.26.18
utilsforecast            0.0.10
uvicorn                  0.27.0.post1
virtualenv               20.21.0
wasabi                   1.1.2
wcwidth                  0.2.13
weasel                   0.3.4
websocket-client         1.7.0
websockets               12.0
Werkzeug                 3.0.1
wheel                    0.42.0
window-ops               0.0.14
xgboost                  2.0.3
xmod                     1.8.1
xxhash                   3.4.1
yarl                     1.9.4
zipp                     3.17.0
```

```python
from autogluon.core.utils import show_versions
show_versions()
```
```Bash
date                   : 2024-01-29
time                   : 17:22:48.832973
python                 : 3.9.18.final.0
OS                     : Windows
OS-release             : 10
Version                : 10.0.22631
machine                : AMD64
processor              : Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
num_cores              : 32
cpu_ram_mb             : 32452.703125
cuda version           : None
num_gpus               : 1
gpu_ram_mb             : [7963]
avail_disk_size_mb     : None

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.34.30
catboost               : 1.2.2
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.13
gluonts                : 0.14.3
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.3
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : 3.8.2
mlforecast             : 0.10.0
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.4
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.12
pandas                 : 2.1.4
Pillow                 : 10.2.0
psutil                 : 5.9.8
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.28.2
scikit-image           : 0.20.0
scikit-learn           : 1.4.0
scikit-learn-intelex   : None
scipy                  : 1.9.1
seqeval                : 1.2.2
setuptools             : 60.2.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.1
tabpfn                 : None
tensorboard            : 2.15.1
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1+cu118
torchmetrics           : 1.1.2
torchvision            : 0.15.2+cu118
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.3
```

**Comment by shchur** [comment] 2024-02-20 10:09
Hi @DiegoDVillacreses, thank you for the detailed bug report. We switched to Ray as the HPO backend for deep learning models like PatchTST in v1.0, so it's likely that Ray is the source of the problem. 

Could you try moving the notebook to a path that doesn't contain spaces? ([Ray may fail because of spaces in file paths](https://discuss.ray.io/t/ray-unable-to-find-worker-py-due-to-spaces-in-filepath-windows/9591))

**Comment by shchur** [comment] 2024-02-20 16:35
According to https://github.com/autogluon/autogluon/issues/3939#issuecomment-1954554220, the problem is most likely caused by the fact that you are using HPO inside a OneDrive directory. Moving outside of the OneDrive directory should fix the issue.

**Comment by shchur** [comment] 2024-03-01 14:49
Closing this issue assuming that https://github.com/autogluon/autogluon/issues/3939#issuecomment-1954554220 provides a solution. Please feel free to re-open if that's not the case.

**Closed by shchur** 2024-03-01 14:49 UTC
Labels: bug: unconfirmed, module: timeseries
